## Validacion de Datos de bancos

In [15]:
from pathlib import Path
import pandas as pd

# Directorio de datos originales
RAW_DIR = Path("data/raw")

# Archivos disponibles
archivo_2009 = "/home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador/data/raw/boletin_mensual/BOL_FIN_BCOS_SEP_09 A.xls"

archivo_2014 = "/home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador/data/raw/cartera_deposito/BANCOS PRIVADOS COLOCACIONES - CONSUMO ENE-DIC 2014.xlsx"

# Abrir los libros
excel_2014 = pd.ExcelFile(archivo_2014)
excel_2009 = pd.ExcelFile(archivo_2009)

print("Hojas del archivo 2014:")
print(excel_2014.sheet_names)

print("\nHojas del archivo 2009:")
print(excel_2009.sheet_names)

Hojas del archivo 2014:
['BANCOS PRIVADOS CONSUMO']

Hojas del archivo 2009:
['BAL SAB II', 'EPyG SAB II', 'CONSCOND', 'BALCONS', 'BALCONS %', 'GRAFICOS', 'RK ', 'GRAF RK', 'COMPOS CART', 'COMPOS CART %', 'CAPCOL x PLAZOS', 'EPyG', 'EPyG %', 'INDIC', 'CARTxPLAZ']

In [16]:
# Cargar indicadores financieros
indicadores = pd.read_excel(
    excel_2009,
    sheet_name="INDIC",
    header=None
)

# Cargar composición de cartera
cartera = pd.read_excel(
    excel_2009,
    sheet_name="COMPOS CART",
    header=None
)

print("Dimensiones de INDIC:", indicadores.shape)
print("Dimensiones de COMPOS CART:", cartera.shape)

display(indicadores.iloc[18:31, :10])

Dimensiones de INDIC: (102, 36)
Dimensiones de COMPOS CART: (75, 36)

,0,1,2,3,4,5,6,7,8,9
18,NaN,NaN,INDICES DE MOROSIDAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,IF28,MOROSIDAD DE LA CARTERA DE CREDITOS COMERCIALES,1.549464,5.839114,2.656962,0.466369,2.376627,8.392526,0.818966
20,NaN,IF29,MOROSIDAD DE LA CARTERA DE CREDITOS DE CONSUMO,3.90864,2.888954,5.495679,4.419331,4.388588,9.163498,4.405068
21,NaN,IF30,MOROSIDAD DE LA CARTERA DE CREDITOS DE VIVIENDA,0.771935,1.148377,1.418651,1.888276,1.311159,2.109428,3.868015
22,NaN,IF31,MOROSIDAD DE LA CARTERA DE CREDITOS PARA LA MI...,0,3.43487,3.465278,5.085958,3.478514,3.521004,0
23,NaN,NaN,MOROSIDAD DE LA CARTERA TOTAL,2.820326,3.693786,3.294239,1.19638,2.99347,8.42018,1.677995
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,COBERTURA DE PROVISIONES PARA CARTERA IMPRODUC...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,COBERTURA DE LA CARTERA COMERCIAL,188.852782,515.580491,488.319301,554.523234,470.421004,64.998244,422.970828
27,NaN,NaN,COBERTURA DE LA CARTERA DE CONSUMO,72.842168,99.655064,183.699694,67.668463,133.687948,78.084465,74.07784
28,NaN,NaN,COBERTURA DE LA CARTERA DE VIVIENDA,146.214011,113.751471,479.322226,134.396515,389.965473,67.720765,38.386609
29,NaN,NaN,COBERTURA DE LA CARTERA DE MICROEMPRESA,0,174.789635,259.74061,98.343776,257.655497,60.105833,0
30,NaN,NaN,COBERTURA DE LA CARTERA PROBLEMÁTICA,95.22804,338.884757,313.744614,222.386722,272.709824,73.034907,195.564502

In [17]:
indicadores.head()

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,INDICADORES FINANCIEROS DEL SISTEMA DE SOCIEDA...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,2009-09-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,(en porcentajes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# Inspeccionar las primeras filas para localizar los nombres de bancos

display(
    indicadores.iloc[:12, :15].T
)

,0,1,2,3,4,5,6,7,8,9,10,11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COD. MAF.,NaN,NaN,IF114,NaN
2,NaN,INDICADORES FINANCIEROS DEL SISTEMA DE SOCIEDA...,SISTEMA DE BANCOS PRIVADOS,2009-09-30 00:00:00,(en porcentajes),NaN,NaN,NOMBRE DEL INDICADOR,NaN,SUFICIENCIA PATRIMONIAL,( PATRIMONIO +RESULTADOS ) / ACTIVOS INMOVILIZ...,PATRIMONIO / ACTIVOS INMOVILIZADOS (DIC)
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP GUAYAQUIL,NaN,NaN,97.032477,84.093205
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP PACIFICO,NaN,NaN,533.241368,486.255184
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP PICHINCHA,NaN,NaN,1028.017957,938.788205
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP PRODUBANCO,NaN,NaN,255.001819,234.313168
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BANCOS PRIVADOS GRANDES,NaN,NaN,312.60064,283.162813
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP AUSTRO,NaN,NaN,138.192333,118.83227
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP BOLIVARIANO,NaN,NaN,210.249821,189.815884
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP GENERAL RUMIÑAHUI,NaN,NaN,350.546244,306.901618
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP INTERNACIONAL,NaN,NaN,219.079344,202.679892
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP MACHALA,NaN,NaN,141.507377,133.433988
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP PROMERICA,NaN,NaN,134.891136,128.585359
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BANCOS PRIVADOS MEDIANOS,NaN,NaN,184.926784,168.07207

catalogo de instituciones

In [19]:
# Extraer nombres de las instituciones financieras
nombres = (
    indicadores.iloc[7, 3:]
    .dropna()
    .astype(str)
    .str.strip()
)

# Construir catálogo de instituciones
catalogo = pd.DataFrame({
    "columna_original": nombres.index,
    "institucion": nombres.values
})

# Clasificar instituciones y agregados
catalogo["tipo"] = catalogo["institucion"].apply(
    lambda x: "Banco" if x.startswith("BP ") else "Agregado"
)

# Visualizar catálogo
display(catalogo)

# Contar registros según clasificación
print("\nResumen:")
print(catalogo["tipo"].value_counts())

    columna_original                      institucion      tipo
0                  3                     BP GUAYAQUIL     Banco
1                  4                      BP PACIFICO     Banco
2                  5                     BP PICHINCHA     Banco
3                  6                    BP PRODUBANCO     Banco
4                  7          BANCOS PRIVADOS GRANDES  Agregado
5                  8                        BP AUSTRO     Banco
6                  9                   BP BOLIVARIANO     Banco
7                 10             BP GENERAL RUMIÑAHUI     Banco
8                 11                 BP INTERNACIONAL     Banco
9                 12                       BP MACHALA     Banco
10                13                     BP PROMERICA     Banco
11                14         BANCOS PRIVADOS MEDIANOS  Agregado
12                15                      BP AMAZONAS     Banco
13                16                      BP CITIBANK     Banco
14                17                        BP COFIEC     Banco
15                18           BP COMERCIAL DE MANABI     Banco
16                19                       BP LITORAL     Banco
17                20                   BP LLOYDS BANK     Banco
18                21                          BP LOJA     Banco
19                22                     BP SOLIDARIO     Banco
20                23                  BP SUDAMERICANO     Banco
21                24                   BP TERRITORIAL     Banco
22                25                      BP UNIBANCO     Banco
23                26                     BP PROCREDIT     Banco
24                27                       BP CAPITAL     Banco
25                28                         BP FINCA     Banco
26                29                       BP DELBANK     Banco
27                30         BANCOS PRIVADOS PEQUEÑOS  Agregado
28                31            TOTAL BANCOS PRIVADOS  Agregado
29                32      BANCOS PRIVADOS COMERCIALES  Agregado
30                33          BANCOS PRIVADOS CONSUMO  Agregado
31                34         BANCOS PRIVADOS VIVIENDA  Agregado
32                35  BANCOS PRIVADOS DE MICROEMPRESA  Agregado

Resumen:
tipo
Banco       25
Agregado     8
Name: count, dtype: int64

In [20]:
# 1. Seleccionar únicamente bancos individuales

bancos = catalogo.loc[
    catalogo["tipo"] == "Banco",
    ["columna_original", "institucion"]
].copy()

# 2. Identificar las filas de los indicadores financieros

filas_indicadores = {
    "morosidad_comercial": 19,
    "morosidad_consumo": 20,
    "morosidad_vivienda": 21,
    "morosidad_microempresa": 22,
    "morosidad_total": 23,
    "cobertura_cartera_problematica": 30
}

# 3. Obtener las columnas correspondientes a bancos

columnas_bancos = bancos["columna_original"].tolist()

# 4. Extraer los valores de cada indicador

for variable, fila in filas_indicadores.items():

    valores = indicadores.iloc[fila, columnas_bancos]

    bancos[variable] = pd.to_numeric(
        valores,
        errors="coerce"
    ).to_numpy()

# 5. Extraer la fecha del boletín financiero

fecha = pd.to_datetime(indicadores.iloc[3, 2])

# Normalizar al primer día del mes
fecha = fecha.to_period("M").to_timestamp()

# 6. Organizar nuestro DataFrame

bancos.insert(0, "fecha", fecha)

bancos = bancos.rename(
    columns={"institucion": "banco"}
)

bancos = bancos.drop(
    columns="columna_original"
)

# 7. Reiniciar los índices

bancos = bancos.reset_index(drop=True)

# 8. Visualizar resultados

display(bancos.head(10))

,fecha,banco,morosidad_comercial,morosidad_consumo,morosidad_vivienda,morosidad_microempresa,morosidad_total,cobertura_cartera_problematica
0,2009-09-01,BP GUAYAQUIL,1.549464,3.908640,0.771935,0.000000,2.820326,95.228040
1,2009-09-01,BP PACIFICO,5.839114,2.888954,1.148377,3.434870,3.693786,338.884757
2,2009-09-01,BP PICHINCHA,2.656962,5.495679,1.418651,3.465278,3.294239,313.744614
3,2009-09-01,BP PRODUBANCO,0.466369,4.419331,1.888276,5.085958,1.196380,222.386722
4,2009-09-01,BP AUSTRO,8.392526,9.163498,2.109428,3.521004,8.420180,73.034907
5,2009-09-01,BP BOLIVARIANO,0.818966,4.405068,3.868015,0.000000,1.677995,195.564502
6,2009-09-01,BP GENERAL RUMIÑAHUI,4.777030,3.353731,5.799863,7.101269,4.523603,120.612777
7,2009-09-01,BP INTERNACIONAL,2.838455,5.177875,1.672050,2.486715,2.758083,101.608081
8,2009-09-01,BP MACHALA,2.012111,5.708310,0.534063,5.579913,3.381360,97.527750
9,2009-09-01,BP PROMERICA,1.542533,7.944056,2.341652,6.308981,2.936572,96.022393

In [21]:
# Dimensiones del dataset
print("Dimensiones:", bancos.shape)

# Tipos de datos
print("\nTipos de datos:")
print(bancos.dtypes)

# Valores faltantes
print("\nValores faltantes:")
print(bancos.isna().sum())

# Registros duplicados por banco y fecha
print("\nDuplicados:")
print(bancos.duplicated(
    subset=["fecha", "banco"]
).sum())

# Comprobar el indicador de Banco Pichincha
print("\nIndicadores de Banco Pichincha:")

display(
    bancos.loc[
        bancos["banco"] == "BP PICHINCHA"
    ]
)

Dimensiones: (25, 8)

Tipos de datos:
fecha                             datetime64[us]
banco                                        str
morosidad_comercial                      float64
morosidad_consumo                        float64
morosidad_vivienda                       float64
morosidad_microempresa                   float64
morosidad_total                          float64
cobertura_cartera_problematica           float64
dtype: object

Valores faltantes:
fecha                             0
banco                             0
morosidad_comercial               0
morosidad_consumo                 0
morosidad_vivienda                0
morosidad_microempresa            0
morosidad_total                   0
cobertura_cartera_problematica    0
dtype: int64

Duplicados:
0

Indicadores de Banco Pichincha:

,fecha,banco,morosidad_comercial,morosidad_consumo,morosidad_vivienda,morosidad_microempresa,morosidad_total,cobertura_cartera_problematica
2,2009-09-01,BP PICHINCHA,2.656962,5.495679,1.418651,3.465278,3.294239,313.744614

### inspeccionar Compos cart

In [22]:
# Dimensiones de la hoja
print("Dimensiones:", cartera.shape)

# Inspeccionar encabezados y primeras filas
display(cartera.iloc[:16, :10])

# Buscar filas relacionadas con cartera bruta e improductiva
patron = r"CARTERA BRUTA|CARTERA IMPRODUCTIVA"

etiquetas = cartera.iloc[:, :4].astype("string")

filas = etiquetas.apply(
    lambda columna: columna.str.contains(
        patron,
        case=False,
        regex=True,
        na=False
    )
).any(axis=1)

display(cartera.loc[filas].iloc[:, :10])

Dimensiones: (75, 36)

,0,1,2,3,4,5,6,7,8,9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,COMPOSICION DE LA CARTERA DE CREDITOS POR VENC...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2009-09-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,(en miles de dólares),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,CODIGO,CUENTA,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,CARTERA BRUTA,1077079.2414,805819.84665,2836288.9457,684945.34512,5404133.37887,375572.32918,634708.27396
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,1401,CARTERA DE CREDITOS COMERCIAL POR VENCER,336189.26948,255867.29377,1024282.56333,535166.38669,2151505.51327,126651.82277,471712.58562
11,NaN,1402,CARTERA DE CREDITOS DE CONSUMO POR VENCER,594544.58302,378514.82888,749516.7896,105930.31298,1828506.51448,191804.26022,105873.97288
12,NaN,1403,CARTERA DE CREDITOS DE VIVIENDA POR VENCER,115968.24505,121471.29065,592791.33369,30672.66838,860903.53777,20513.84478,45319.81458
13,NaN,1404,CARTERA DE CREDITOS PARA LA MICROEMPRESA POR V...,0,523.2808,360319.46221,2934.48016,363777.22317,4125.84715,0
14,NaN,1405,CARTERA DE CREDITOS COMERCIAL REESTRUCTURADA P...,0,19371.69274,15052.56021,973.38733,35397.64028,459.04801,0
15,NaN,1406,CARTERA DE CREDITOS DE CONSUMO REESTRUCTURADA ...,0,16.85454,33.84317,605.45775,656.15546,360.52658,1151.52758

,0,1,2,3,4,5,6,7,8,9
8,NaN,NaN,CARTERA BRUTA,1077079.2414,805819.84665,2836288.9457,684945.34512,5404133.37887,375572.32918,634708.27396
49,NaN,NaN,CARTERA IMPRODUCTIVA COMERCIAL,5291.11438,17068.14682,28368.47634,2512.10353,53239.84107,11645.13416,3895.06725
50,NaN,NaN,CARTERA IMPRODUCTIVA CONSUMO,24183.86591,11260.92953,43588.37459,4925.85811,83959.02814,19385.39727,4931.79498
51,NaN,NaN,CARTERA IMPRODUCTIVA VIVIENDA,902.16356,1413.03222,8543.01286,599.34086,11457.5495,442.76297,1823.51107
52,NaN,NaN,CARTERA IMPRODUCTIVA MICROEMPRESA,0,23.15385,12934.27862,157.24379,13114.67626,150.57294,0
53,NaN,NaN,TOTAL CARTERA IMPRODUCTIVA (NO DEVENGA INTERE...,30377.14385,29765.26242,93434.14241,8194.54629,161771.09497,31623.86734,10650.3733
55,NaN,NaN,CARTERA BRUTA COMERCIAL,341480.38386,292307.13333,1067703.59988,538651.87755,2240142.99462,138756.00494,475607.65287
56,NaN,NaN,CARTERA BRUTA CONSUMO,618728.44893,389792.61295,793139.00736,111461.62884,1913121.69808,211550.18407,111957.29544
57,NaN,NaN,CARTERA BRUTA VIVIENDA,116870.40861,123046.01816,602192.59763,31740.11478,873849.13918,20989.72008,47143.32565
58,NaN,NaN,CARTERA BRUTA MICROEMPRESA,0,674.08221,373253.74083,3091.72395,377019.54699,4276.42009,0
59,NaN,NaN,TOTAL CARTERA BRUTA,1077079.2414,805819.84665,2836288.9457,684945.34512,5404133.37887,375572.32918,634708.27396

In [23]:
# 1. Obtener los nombres de las instituciones en COMPOS CART

nombres_cartera = (
    cartera.iloc[6, 3:]
    .dropna()
    .astype(str)
    .str.strip()
)

# Conservar solamente los bancos individuales
nombres_cartera = nombres_cartera[
    nombres_cartera.str.startswith("BP ")
]

# 2. Identificar sus columnas originales

columnas = nombres_cartera.index

# 3. Extraer los saldos financieros

saldos = pd.DataFrame({
    "banco": nombres_cartera.values,

    "cartera_bruta": pd.to_numeric(
        cartera.loc[59, columnas],
        errors="coerce"
    ).to_numpy(),

    "cartera_improductiva": pd.to_numeric(
        cartera.loc[53, columnas],
        errors="coerce"
    ).to_numpy()
})

# 4. Calcular la morosidad

denominador = saldos["cartera_bruta"].where(
    saldos["cartera_bruta"] > 0
)

saldos["morosidad_calculada"] = (
    saldos["cartera_improductiva"] / denominador
) * 100

# 5. Comparar con la morosidad publicada en INDIC

validacion = bancos[
    ["banco", "morosidad_total"]
].merge(
    saldos,
    on="banco",
    how="left",
    validate="one_to_one"
)

# 6. Calcular diferencia absoluta en puntos porcentuales

validacion["diferencia_pp"] = (
    validacion["morosidad_total"]
    - validacion["morosidad_calculada"]
).abs()

# 7. Mostrar resultados

display(validacion)

,banco,morosidad_total,cartera_bruta,cartera_improductiva,morosidad_calculada,diferencia_pp
0,BP GUAYAQUIL,2.820326,1.077079e+06,30377.14385,2.820326,0.0
1,BP PACIFICO,3.693786,8.058198e+05,29765.26242,3.693786,0.0
2,BP PICHINCHA,3.294239,2.836289e+06,93434.14241,3.294239,0.0
3,BP PRODUBANCO,1.196380,6.849453e+05,8194.54629,1.196380,0.0
4,BP AUSTRO,8.420180,3.755723e+05,31623.86734,8.420180,0.0
5,BP BOLIVARIANO,1.677995,6.347083e+05,10650.37330,1.677995,0.0
6,BP GENERAL RUMIÑAHUI,4.523603,1.986914e+05,8988.00886,4.523603,0.0
7,BP INTERNACIONAL,2.758083,7.554464e+05,20835.83889,2.758083,0.0
8,BP MACHALA,3.381360,1.947916e+05,6586.60466,3.381360,0.0
9,BP PROMERICA,2.936572,2.585490e+05,7592.47698,2.936572,0.0
10,BP AMAZONAS,3.297416,5.914252e+04,1950.17491,3.297416,0.0
11,BP CITIBANK,0.021447,1.072435e+05,23.00000,0.021447,0.0
12,BP COFIEC,23.625000,7.281967e+03,1720.36477,23.625000,0.0
13,BP COMERCIAL DE MANABI,7.572641,1.385030e+04,1048.83351,7.572641,0.0
14,BP LITORAL,5.110259,1.056798e+04,540.05103,5.110259,0.0
15,BP LLOYDS BANK,0.002313,1.297128e+05,3.00000,0.002313,0.0
16,BP LOJA,3.586670,1.100782e+05,3948.14170,3.586670,0.0
17,BP SOLIDARIO,7.320684,2.218861e+05,16243.57826,7.320684,0.0
18,BP SUDAMERICANO,6.778027,2.625325e+03,177.94523,6.778027,0.0
19,BP TERRITORIAL,9.956624,8.274603e+04,8238.71033,9.956624,0.0
20,BP UNIBANCO,7.172645,1.594530e+05,11437.00000,7.172645,0.0
21,BP PROCREDIT,3.014568,2.275827e+05,6860.63689,3.014568,0.0
22,BP CAPITAL,10.404054,3.404995e+04,3542.57551,10.404054,0.0
23,BP FINCA,11.240542,2.587722e+04,2908.74000,11.240542,0.0
24,BP DELBANK,4.378598,7.719187e+03,337.99221,4.378598,0.0

In [24]:
# Tolerancia en puntos porcentuales
tolerancia = 0.0001

# Comprobar registros no verificables
no_verificables = validacion[
    validacion["morosidad_calculada"].isna()
]

# Identificar diferencias superiores a la tolerancia
diferencias = validacion[
    validacion["diferencia_pp"] > tolerancia
]

print("Total de bancos:", len(validacion))

print(
    "Bancos sin cálculo verificable:",
    len(no_verificables)
)

print(
    "Bancos con diferencias relevantes:",
    len(diferencias)
)

print(
    "Diferencia máxima:",
    validacion["diferencia_pp"].max()
)

# Mostrar los mayores errores
display(
    validacion.sort_values(
        "diferencia_pp",
        ascending=False
    ).head(10)
)

# Mostrar bancos que requieren revisión
if not no_verificables.empty or not diferencias.empty:
    display(
        validacion.loc[
            validacion["morosidad_calculada"].isna()
            | (validacion["diferencia_pp"] > tolerancia)
        ]
    )

Total de bancos: 25
Bancos sin cálculo verificable: 0
Bancos con diferencias relevantes: 0
Diferencia máxima: 0.0

,banco,morosidad_total,cartera_bruta,cartera_improductiva,morosidad_calculada,diferencia_pp
0,BP GUAYAQUIL,2.820326,1.077079e+06,30377.14385,2.820326,0.0
1,BP PACIFICO,3.693786,8.058198e+05,29765.26242,3.693786,0.0
2,BP PICHINCHA,3.294239,2.836289e+06,93434.14241,3.294239,0.0
3,BP PRODUBANCO,1.196380,6.849453e+05,8194.54629,1.196380,0.0
4,BP AUSTRO,8.420180,3.755723e+05,31623.86734,8.420180,0.0
5,BP BOLIVARIANO,1.677995,6.347083e+05,10650.37330,1.677995,0.0
6,BP GENERAL RUMIÑAHUI,4.523603,1.986914e+05,8988.00886,4.523603,0.0
7,BP INTERNACIONAL,2.758083,7.554464e+05,20835.83889,2.758083,0.0
8,BP MACHALA,3.381360,1.947916e+05,6586.60466,3.381360,0.0
9,BP PROMERICA,2.936572,2.585490e+05,7592.47698,2.936572,0.0

In [25]:
# Nombre registrado en INDIC
nombre_indic = bancos.loc[
    bancos["banco"].str.contains("GUAYAQUIL"),
    "banco"
].iloc[0]

# Nombre registrado en COMPOS CART
nombre_cartera = cartera.iloc[6, 4]

print("Nombre INDIC:")
print(repr(nombre_indic))

print("\nNombre COMPOS CART:")
print(repr(nombre_cartera))

print("\n¿Son iguales?")
print(nombre_indic == nombre_cartera)

print("\n¿Banco Guayaquil aparece en saldos?")
print(
    saldos["banco"].str.contains(
        "GUAYAQUIL",
        case=False,
        na=False
    ).any()
)

Nombre INDIC:
'BP GUAYAQUIL'

Nombre COMPOS CART:
'BP PACIFICO'

¿Son iguales?
False

¿Banco Guayaquil aparece en saldos?
True

In [26]:
import unicodedata


def normalizar_nombre(nombre):
    """Normaliza nombres de instituciones financieras."""

    nombre = unicodedata.normalize(
        "NFKC",
        str(nombre)
    )

    nombre = " ".join(nombre.upper().split())

    return nombre

In [27]:
print(normalizar_nombre("BP  GUAYAQUIL"))
print(normalizar_nombre(" BP GUAYAQUIL "))

BP GUAYAQUIL
BP GUAYAQUIL

## Series por banco

In [28]:
from pathlib import Path
import pandas as pd

# Directorio de series históricas
SERIES_DIR = Path("/home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador/data/raw/series_entidad/BP PICHINCHA DIC 2020 web.xlsx")

series_bp_2020 = "/home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador/data/raw/series_entidad/BP PICHINCHA DIC 2020 web.xlsx"

# Abrir el primer archivo
excel_historico = pd.ExcelFile(series_bp_2020)

print("\nHojas disponibles:")
for hoja in excel_historico.sheet_names:
    print(hoja)

FileNotFoundError: [Errno 2] No such file or directory: '/home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador/data/raw/series_entidad/BP PICHINCHA DIC 2020 web.xlsx'

In [ ]:
# Examinar las primeras tres hojas

for hoja in excel_historico.sheet_names[:3]:

    df = pd.read_excel(
        excel_historico,
        sheet_name=hoja,
        header=None,
        nrows=12
    )

    print(f"\nHOJA: {hoja}")
    print(f"Dimensiones de la muestra: {df.shape}")

    display(df.iloc[:, :10])

HOJA: BAL
Dimensiones de la muestra: (12, 227)

,0,1,2,3,4,5,6,7,8,9
0,NaN,COMPARATIVO DE SITUACIÓN NOMINAL,NaN,0,0,0,0,0,0,-0.0
1,NaN,BP PICHINCHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,( en miles de dólares),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,7,8,9,10,11,12,1
4,NaN,CÓDIGO,CUENTA,2002-07-31 00:00:00,2002-08-31 00:00:00,2002-09-30 00:00:00,2002-10-31 00:00:00,2002-11-30 00:00:00,2002-12-31 00:00:00,2003-01-31 00:00:00
5,NaN,NaN,ACTIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2.0,11,FONDOS DISPONIBLES,NaN,NaN,NaN,NaN,NaN,NaN,285082.82184
7,4.0,1101,Caja,NaN,NaN,NaN,NaN,NaN,NaN,34424.07307
8,6.0,110105,Efectivo,NaN,NaN,NaN,NaN,NaN,NaN,34419.13531
9,6.0,110110,Caja chica,NaN,NaN,NaN,NaN,NaN,NaN,4.93776
10,4.0,1102,Depósitos para encaje,NaN,NaN,NaN,NaN,NaN,NaN,38537.23304
11,6.0,110205,Banco Central del Ecuador,NaN,NaN,NaN,NaN,NaN,NaN,37137.8103

HOJA: PYG
Dimensiones de la muestra: (12, 227)

,0,1,2,3,4,5,6,7,8,9
0,NaN,COMPARATIVO DEL ESTADO DE RESULTADOS NOMINAL,NaN,0,0,0,0,0,0,-0.0
1,NaN,BP PICHINCHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,(en miles de dólares),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,7,8,9,10,11,12,1
4,NaN,CÓDIGO,CUENTA,2002-07-31 00:00:00,2002-08-31 00:00:00,2002-09-30 00:00:00,2002-10-31 00:00:00,2002-11-30 00:00:00,2002-12-31 00:00:00,2003-01-31 00:00:00
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1.0,5,TOTAL INGRESOS,NaN,NaN,NaN,NaN,NaN,NaN,20020.46881
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2.0,51,INTERESES Y DESCUENTOS GANADOS,NaN,NaN,NaN,NaN,NaN,NaN,10494.1974
10,4.0,5101,Depósitos,NaN,NaN,NaN,NaN,NaN,NaN,75.29843
11,4.0,5102,Operaciones interbancarias,NaN,NaN,NaN,NaN,NaN,NaN,0.38197

HOJA: BAL %
Dimensiones de la muestra: (12, 225)

,0,1,2,3,4,5,6,7,8,9
0,NaN,ESTRUCTURA PORCENTUAL DEL COMPARATIVO DE SITUA...,NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaN
1,NaN,BP PICHINCHA,NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaN
2,NaN,( en porcentajes),NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaN
3,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaN
4,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaN
5,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaN
6,NaN,CÓDIGO,CUENTA,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31 00:00:00
7,NaN,0,ACTIVO,NaT,NaT,NaT,NaT,NaT,NaT,NaN
8,NaN,11,FONDOS DISPONIBLES,NaT,NaT,NaT,NaT,NaT,NaT,0.188829
9,NaN,1101,Caja,NaT,NaT,NaT,NaT,NaT,NaT,0.022801
10,NaN,1102,Depósitos para encaje,NaT,NaT,NaT,NaT,NaT,NaT,0.025526
11,NaN,1103,Bancos y otras instituciones financieras,NaT,NaT,NaT,NaT,NaT,NaT,0.113443

In [ ]:
# muestra la hoja INDICAD de excel_historico
display(excel_historico.parse("INDICAD"))

,Unnamed: 0,Unnamed: 1,INDICADORES FINANCIEROS,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 215,Unnamed: 216,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220,Unnamed: 221,Unnamed: 222,Unnamed: 223,Unnamed: 224
0,NaN,NaN,BP PICHINCHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,(En porcentajes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,NaN,Intermediación,Intermediación,NaN,NaN,NaN,NaN,NaN,NaN,0.646335,...,0.9357,0.880268,0.832645,0.810721,0.79526,0.773479,0.771517,0.740209,0.772611,0.735453
92,NaN,Cartera Bruta,CARTERA BRUTA,0,0,0,0,0,0,773223.27405,...,7887513.47149,7457779.71628,7240607.70822,7203594.41644,7039611.95697,6935912.98051,6936956.81604,7006014.03131,7090315.67444,7200026.16555
93,NaN,Obligaciones con el Público (Dep. vista+ De...,Depósitos a la vista + Depósitos a plazo,0,0,0,0,0,0,1196320.49622,...,8429531.19782,8472172.60752,8695907.45061,8885414.12962,8851958.96405,8967158.71899,8991321.3696,9464917.13467,9177088.55802,9789924.97436

In [29]:
# Cargar los indicadores históricos
indicad = pd.read_excel(
    excel_historico,
    sheet_name="INDICAD",
    header=None
)

print("Dimensiones:", indicad.shape)

# Inspeccionar encabezados
display(indicad.iloc[:12, :12])

NameError: name 'excel_historico' is not defined

In [30]:
# Indicadores financieros de interés
patron = (
    r"MOROSIDAD|CARTERA BRUTA|CARTERA IMPRODUCTIVA|"
    r"LIQUIDEZ|COBERTURA|ROA|ROE"
)

# Buscar indicadores en las primeras cuatro columnas
etiquetas = indicad.iloc[:, :4].astype("string")

coincidencias = etiquetas.apply(
    lambda columna: columna.str.contains(
        patron,
        case=False,
        regex=True,
        na=False
    )
).any(axis=1)

# Mostrar filas encontradas
display(
    indicad.loc[coincidencias]
    .iloc[:, :8]
)

NameError: name 'indicad' is not defined

In [31]:
from pathlib import Path
import pandas as pd
import numpy as np

# Ruta del archivo
series_bp_2020 = "/home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador/data/raw/series_entidad/BP PICHINCHA DIC 2020 web.xlsx"

# Cargar únicamente los indicadores financieros
historico = pd.read_excel(
    series_bp_2020,
    sheet_name="INDICAD",
    header=None
)

# 1. Extraer fechas
fechas_originales = historico.iloc[6, 4:]

fechas = pd.to_datetime(
    fechas_originales,
    errors="coerce"
)

# Convertir fechas seriales de Excel si fuera necesario
es_numero = fechas_originales.map(
    lambda x: isinstance(
        x, (int, float, np.integer, np.floating)
    )
)

# Convertir fechas seriales de Excel únicamente si existen
if es_numero.any():
    fechas_seriales = pd.to_numeric(
        fechas_originales.loc[es_numero],
        errors="coerce"
    )

    fechas.loc[es_numero] = pd.to_datetime(
        fechas_seriales,
        unit="D",
        origin="1899-12-30",
        errors="coerce"
    )

# 2. Extraer los indicadores
serie_pichincha = pd.DataFrame({
    "fecha": fechas,
    "morosidad_total": pd.to_numeric(
        historico.iloc[78, 3:], errors="coerce"
    ) * 100,

    "cartera_bruta": pd.to_numeric(
        historico.iloc[80, 3:], errors="coerce"
    ),

    "cartera_improductiva": pd.to_numeric(
        historico.iloc[79, 3:], errors="coerce"
    ),

    "liquidez": pd.to_numeric(
        historico.iloc[28, 3:], errors="coerce"
    ) * 100,

    "roa": pd.to_numeric(
        historico.iloc[33, 3:], errors="coerce"
    ) * 100,

    "roe": pd.to_numeric(
        historico.iloc[35, 3:], errors="coerce"
    ) * 100,

    "cobertura": pd.to_numeric(
        historico.iloc[83, 3:], errors="coerce"
    ) * 100
})

# 3. Eliminar períodos sin cartera bruta válida
serie_pichincha = serie_pichincha.loc[
    serie_pichincha["cartera_bruta"] > 0
].copy()

# 4. Normalizar fechas
serie_pichincha["fecha"] = (
    pd.to_datetime(serie_pichincha["fecha"])
    .dt.to_period("M")
    .dt.to_timestamp()
)

# 5. Incorporar la institución
serie_pichincha.insert(
    1, "banco", "BP PICHINCHA"
)

# 6. Reiniciar índices y ordenar
serie_pichincha = (
    serie_pichincha
    .sort_values("fecha")
    .reset_index(drop=True)
)

# Visualización
display(serie_pichincha.head())
display(serie_pichincha.tail())

FileNotFoundError: [Errno 2] No such file or directory: '/home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador/data/raw/series_entidad/BP PICHINCHA DIC 2020 web.xlsx'

In [ ]:
# 1. Información general

print("Dimensiones:", serie_pichincha.shape)

print("\nPeríodo:")
print("Inicio:", serie_pichincha["fecha"].min())
print("Fin:", serie_pichincha["fecha"].max())


# 2. Verificar valores faltantes

print("\nValores faltantes:")
print(serie_pichincha.isna().sum())


# 3. Verificar duplicados

duplicados = serie_pichincha.duplicated(
    subset=["fecha", "banco"]
).sum()

print("\nDuplicados:", duplicados)


# 4. Verificar continuidad mensual

periodos = pd.PeriodIndex(
    serie_pichincha["fecha"],
    freq="M"
)

periodos_esperados = pd.period_range(
    start=periodos.min(),
    end=periodos.max(),
    freq="M"
)

meses_faltantes = periodos_esperados.difference(
    periodos
)

print("\nMeses esperados:", len(periodos_esperados))
print("Meses observados:", len(periodos))
print("Meses faltantes:", len(meses_faltantes))

if len(meses_faltantes) > 0:
    print(meses_faltantes)


# 5. Validación financiera

morosidad_calculada = (
    serie_pichincha["cartera_improductiva"]
    / serie_pichincha["cartera_bruta"]
) * 100

diferencia = (
    serie_pichincha["morosidad_total"]
    - morosidad_calculada
).abs()

print("\nVALIDACIÓN FINANCIERA")

print(
    "Diferencia máxima:",
    diferencia.max()
)

print(
    "Meses con diferencias > 0.0001 pp:",
    (diferencia > 0.0001).sum()
)

print(
    "Meses sin comparación válida:",
    diferencia.isna().sum()
)

Dimensiones: (216, 9)

Período:
Inicio: 2003-01-01 00:00:00
Fin: 2020-12-01 00:00:00

Valores faltantes:
fecha                   0
banco                   0
morosidad_total         0
cartera_bruta           0
cartera_improductiva    0
liquidez                0
roa                     0
roe                     0
cobertura               0
dtype: int64

Duplicados: 0

Meses esperados: 216
Meses observados: 216
Meses faltantes: 0

VALIDACIÓN FINANCIERA
Diferencia máxima: 0.0
Meses con diferencias > 0.0001 pp: 0
Meses sin comparación válida: 0

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

# Identificar la raíz del proyecto
cwd = Path.cwd().resolve()

PROJECT_ROOT = next(
    (
        ruta
        for ruta in (cwd, *cwd.parents)
        if (ruta / "data" / "raw").is_dir()
        and (ruta / "notebooks").is_dir()
    ),
    None
)

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "No se pudo identificar la raíz del proyecto."
    )

# Directorios
DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"

BOLETINES_DIR = RAW_DIR / "boletin_mensual"
CARTERA_DIR = RAW_DIR / "cartera_deposito"
SERIES_DIR = RAW_DIR / "series_entidad"

print("Raíz del proyecto:", PROJECT_ROOT)
print("Directorio de series:", SERIES_DIR)

Raíz del proyecto: /home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador
Directorio de series: /home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador/data/raw/series_entidad

In [33]:
# Ruta del boletín histórico más reciente
series_bp_2026 = (
    SERIES_DIR / "BP PICHINCHA 2026_09.xlsx"
)

# Cargar las dos hojas principales
indicad_2026 = pd.read_excel(
    series_bp_2026,
    sheet_name="INDICAD",
    header=None
)

cartera_2026 = pd.read_excel(
    series_bp_2026,
    sheet_name="INDIC CARTERA",
    header=None
)

# Dimensiones
print("INDICAD:", indicad_2026.shape)
print("INDIC CARTERA:", cartera_2026.shape)

# Inspeccionar indicadores seleccionados
print("\nIndicadores financieros:")

display(
    indicad_2026.iloc[
        [6, 8, 15, 19, 21, 33],
        :7
    ]
)

print("\nIndicadores de cartera:")

display(
    cartera_2026.iloc[
        [4, 18, 40, 92, 105],
        :8
    ]
)

INDICAD: (47, 286)
INDIC CARTERA: (583, 288)

Indicadores financieros:

,0,1,2,3,4,5,6
6,RATIOS,2003-01-31 00:00:00,2003-02-28 00:00:00,2003-03-31 00:00:00,2003-04-30 00:00:00,2003-05-31 00:00:00,2003-06-30 00:00:00
8,SOLVENCIA,0.09746,0.09606,0.09574,0.09577,0.09536,0.09285
15,FONDOS DISPONIBLES / TOTAL DEPOSITOS A CORTO P...,0.250819,0.253485,0.284911,0.307123,0.321989,0.267446
19,ROA,0.008031,0.00838,0.008533,0.00955,0.010346,0.011898
21,ROE,0.079752,0.083619,0.086135,0.09731,0.10685,0.123597
33,CARTERA / DEPÓSITOS,0.576842,0.558396,0.544412,0.535942,0.531383,0.540778

Indicadores de cartera:

,0,1,2,3,4,5,6,7
4,ITEM,FÓRMULA,VARIABLES,2003-01-31 00:00:00,2003-02-28 00:00:00,2003-03-31 00:00:00,2003-04-30 00:00:00,2003-05-31 00:00:00
18,(r),(d)+(e)+(f)+(g)+(h)+(i),CARTERA BRUTA,773223.27405,765411.25419,763376.48744,766365.30047,781683.97139
40,(aw),(q)+(r)+(s)+(t)+(u)+(v)+(w),TOTAL CARTERA IMPRODUCTIVA,49264.56653,54264.73903,58174.31695,59516.50111,66443.03852
92,(cw),CARTERA IMPRODUCTIVA TOTAL / TOTAL CARTERA BRUTA,Morosidad Total,0.063713,0.070896,0.076207,0.077661,0.085
105,(dn),(b) / (aw),COBERTURA TOTAL CARTERA,1.685344,1.561082,1.487067,1.463354,1.316065

In [34]:
# Extraer fechas de ambas hojas

fechas_indicad = pd.to_datetime(
    indicad_2026.iloc[6, 2:],
    errors="coerce"
).dropna()

fechas_cartera = pd.to_datetime(
    cartera_2026.iloc[4, 4:],
    errors="coerce"
).dropna()


def verificar_fechas(fechas, nombre):

    periodos = fechas.dt.to_period("M")

    esperados = pd.period_range(
        start=periodos.min(),
        end=periodos.max(),
        freq="M"
    )

    faltantes = esperados.difference(periodos)

    print(f"\nHOJA: {nombre}")
    print("Primera fecha:", fechas.min())
    print("Última fecha:", fechas.max())
    print("Observaciones:", len(fechas))
    print("Meses faltantes:", len(faltantes))
    print("Meses duplicados:", periodos.duplicated().sum())

    if len(faltantes) > 0:
        print("Períodos faltantes:", faltantes.tolist())


verificar_fechas(fechas_indicad, "INDICAD")
verificar_fechas(fechas_cartera, "INDIC CARTERA")

# Comprobar coincidencia entre períodos
periodos_indicad = pd.PeriodIndex(fechas_indicad, freq="M")
periodos_cartera = pd.PeriodIndex(fechas_cartera, freq="M")

print("\n¿Ambas hojas contienen los mismos meses?")
print(
    set(periodos_indicad) == set(periodos_cartera)
)

HOJA: INDICAD
Primera fecha: 2003-02-28 00:00:00
Última fecha: 2026-09-30 00:00:00
Observaciones: 284
Meses faltantes: 0
Meses duplicados: 0

HOJA: INDIC CARTERA
Primera fecha: 2003-02-28 00:00:00
Última fecha: 2026-09-30 00:00:00
Observaciones: 284
Meses faltantes: 0
Meses duplicados: 0

¿Ambas hojas contienen los mismos meses?
True

In [35]:
def extraer_hoja(df, fila_fechas, columna_inicio, variables):
    """
    Extrae indicadores financieros históricos de una hoja Excel.

    Parámetros
    ----------
    df : pd.DataFrame
        Hoja original cargada con header=None.

    fila_fechas : int
        Fila que contiene las fechas.

    columna_inicio : int
        Primera columna con datos temporales.

    variables : dict
        Diccionario {nombre_variable: fila_original}.

    Retorna
    -------
    pd.DataFrame
        Serie temporal con fechas e indicadores.
    """

    # Extraer fechas válidas
    fechas = pd.to_datetime(
        df.iloc[fila_fechas, columna_inicio:],
        errors="coerce"
    ).dropna()

    # Crear DataFrame
    resultado = pd.DataFrame({
        "fecha": fechas.dt.to_period("M").dt.to_timestamp().to_numpy()
    })

    # Extraer cada indicador
    for nombre, fila in variables.items():

        valores = pd.to_numeric(
            df.loc[fila, fechas.index],
            errors="coerce"
        )

        resultado[nombre] = valores.to_numpy()

    return resultado

In [36]:
# Indicadores financieros
variables_financieras = {
    "solvencia": 8,
    "liquidez": 15,
    "roa": 19,
    "roe": 21,
    "cartera_depositos": 33
}

# Indicadores de cartera
variables_cartera = {
    "cartera_bruta": 18,
    "cartera_improductiva": 40,
    "morosidad_total": 92,
    "cobertura": 105
}

# Extraer indicadores financieros
df_financiero = extraer_hoja(
    indicad_2026,
    fila_fechas=6,
    columna_inicio=1,
    variables=variables_financieras
)

# Extraer indicadores de cartera
df_cartera = extraer_hoja(
    cartera_2026,
    fila_fechas=4,
    columna_inicio=3,
    variables=variables_cartera
)

# Verificar resultados
print("Indicadores financieros:", df_financiero.shape)
print("Indicadores de cartera:", df_cartera.shape)

print("\nPrimera fecha financiera:", df_financiero["fecha"].min())
print("Primera fecha cartera:", df_cartera["fecha"].min())

print("\nÚltima fecha financiera:", df_financiero["fecha"].max())
print("Última fecha cartera:", df_cartera["fecha"].max())

display(df_financiero.head(3))
display(df_cartera.head(3))

Indicadores financieros: (285, 6)
Indicadores de cartera: (285, 5)

Primera fecha financiera: 2003-01-01 00:00:00
Primera fecha cartera: 2003-01-01 00:00:00

Última fecha financiera: 2026-09-01 00:00:00
Última fecha cartera: 2026-09-01 00:00:00

       fecha  solvencia  liquidez       roa       roe  cartera_depositos
0 2003-01-01    0.09746  0.250819  0.008031  0.079752           0.576842
1 2003-02-01    0.09606  0.253485  0.008380  0.083619           0.558396
2 2003-03-01    0.09574  0.284911  0.008533  0.086135           0.544412

       fecha  cartera_bruta  cartera_improductiva  morosidad_total  cobertura
0 2003-01-01   773223.27405           49264.56653         0.063713   1.685344
1 2003-02-01   765411.25419           54264.73903         0.070896   1.561082
2 2003-03-01   763376.48744           58174.31695         0.076207   1.487067

In [37]:
# Comprobar que no existen fechas duplicadas
assert df_financiero["fecha"].is_unique
assert df_cartera["fecha"].is_unique

# Comprobar que ambas hojas tienen los mismos períodos
assert set(df_financiero["fecha"]) == set(df_cartera["fecha"])

# Integrar indicadores
serie_bp_2026 = df_financiero.merge(
    df_cartera,
    on="fecha",
    how="inner",
    validate="one_to_one"
)

# Incorporar nombre de la institución
serie_bp_2026.insert(
    1,
    "banco",
    "BP PICHINCHA"
)

# Ordenar cronológicamente
serie_bp_2026 = (
    serie_bp_2026
    .sort_values("fecha")
    .reset_index(drop=True)
)

# Comprobar dimensiones
print("Dimensiones:", serie_bp_2026.shape)

display(serie_bp_2026.head())
display(serie_bp_2026.tail())

Dimensiones: (285, 11)

,fecha,banco,solvencia,liquidez,roa,roe,cartera_depositos,cartera_bruta,cartera_improductiva,morosidad_total,cobertura
0,2003-01-01,BP PICHINCHA,0.09746,0.250819,0.008031,0.079752,0.576842,773223.27405,49264.56653,0.063713,1.685344
1,2003-02-01,BP PICHINCHA,0.09606,0.253485,0.008380,0.083619,0.558396,765411.25419,54264.73903,0.070896,1.561082
2,2003-03-01,BP PICHINCHA,0.09574,0.284911,0.008533,0.086135,0.544412,763376.48744,58174.31695,0.076207,1.487067
3,2003-04-01,BP PICHINCHA,0.09577,0.307123,0.009550,0.097310,0.535942,766365.30047,59516.50111,0.077661,1.463354
4,2003-05-01,BP PICHINCHA,0.09536,0.321989,0.010346,0.106850,0.531383,781683.97139,66443.03852,0.085000,1.316065

,fecha,banco,solvencia,liquidez,roa,roe,cartera_depositos,cartera_bruta,cartera_improductiva,morosidad_total,cobertura
280,2026-05-01,BP PICHINCHA,0.139396,0.138527,0.011290,0.115696,0.668521,1.451085e+07,596093.68480,0.041079,2.802992
281,2026-06-01,BP PICHINCHA,0.137124,0.109264,0.011460,0.117935,0.691242,1.477456e+07,562860.39426,0.038097,2.957710
282,2026-07-01,BP PICHINCHA,0.136285,0.138124,0.011255,0.116374,0.690550,1.496336e+07,565601.47258,0.037799,3.051334
283,2026-08-01,BP PICHINCHA,0.134194,0.136341,0.011082,0.115237,0.684445,1.510220e+07,581796.80176,0.038524,2.996278
284,2026-09-01,BP PICHINCHA,NaN,0.130978,0.010956,0.114411,0.685097,1.499439e+07,551018.52516,0.036748,3.116224

In [38]:
import numpy as np

# 1. Dimensiones
print("Dimensiones:", serie_bp_2026.shape)

# 2. Valores faltantes
print("\nValores faltantes:")
print(serie_bp_2026.isna().sum())

# 3. Duplicados
duplicados = serie_bp_2026.duplicated(
    subset=["fecha", "banco"]
).sum()

print("\nDuplicados:", duplicados)

# 4. Continuidad temporal
periodos = pd.PeriodIndex(
    serie_bp_2026["fecha"],
    freq="M"
)

esperados = pd.period_range(
    periodos.min(),
    periodos.max(),
    freq="M"
)

faltantes = esperados.difference(periodos)

print("\nMeses esperados:", len(esperados))
print("Meses observados:", len(periodos))
print("Meses faltantes:", len(faltantes))

# 5. Consistencia financiera
morosidad_calculada = (
    serie_bp_2026["cartera_improductiva"]
    / serie_bp_2026["cartera_bruta"]
)

diferencia = (
    serie_bp_2026["morosidad_total"]
    - morosidad_calculada
).abs()

tolerancia = 1e-8

print("\nVALIDACIÓN FINANCIERA")
print("Diferencia máxima:", diferencia.max())

print(
    "Meses con diferencias relevantes:",
    (diferencia > tolerancia).sum()
)

print(
    "Meses sin comparación válida:",
    diferencia.isna().sum()
)

Dimensiones: (285, 11)

Valores faltantes:
fecha                   0
banco                   0
solvencia               1
liquidez                0
roa                     0
roe                     0
cartera_depositos       0
cartera_bruta           0
cartera_improductiva    0
morosidad_total         0
cobertura               0
dtype: int64

Duplicados: 0

Meses esperados: 285
Meses observados: 285
Meses faltantes: 0

VALIDACIÓN FINANCIERA
Diferencia máxima: 4.98856338182474e-11
Meses con diferencias relevantes: 0
Meses sin comparación válida: 0

In [39]:
# Identificar el período con solvencia faltante

display(
    serie_bp_2026.loc[
        serie_bp_2026["solvencia"].isna(),
        ["fecha", "banco", "solvencia"]
    ]
)

         fecha         banco  solvencia
284 2026-09-01  BP PICHINCHA        NaN

In [40]:
def extraer_serie_banco(ruta_archivo):
    """
    Extrae los indicadores históricos de una institución
    financiera a partir de su boletín de series.
    """

    # 1. Abrir archivo
    excel = pd.ExcelFile(ruta_archivo)

    indicad = pd.read_excel(
        excel,
        sheet_name="INDICAD",
        header=None
    )

    cartera = pd.read_excel(
        excel,
        sheet_name="INDIC CARTERA",
        header=None
    )

    # 2. Identificar institución
    banco = str(indicad.iloc[1, 0]).strip()

    banco_cartera = str(cartera.iloc[1, 0]).strip()

    if banco != banco_cartera:
        raise ValueError(
            f"Instituciones diferentes: {banco} y {banco_cartera}"
        )

    # 3. Verificar indicadores principales
    if str(indicad.iloc[8, 0]).strip().upper() != "SOLVENCIA":
        raise ValueError("No se encontró SOLVENCIA en la fila esperada.")

    if str(cartera.iloc[92, 2]).strip().upper() != "MOROSIDAD TOTAL":
        raise ValueError("No se encontró MOROSIDAD TOTAL en la fila esperada.")

    # 4. Extraer indicadores financieros
    df_financiero = extraer_hoja(
        indicad,
        fila_fechas=6,
        columna_inicio=1,
        variables=variables_financieras
    )

    # 5. Extraer indicadores de cartera
    df_cartera = extraer_hoja(
        cartera,
        fila_fechas=4,
        columna_inicio=3,
        variables=variables_cartera
    )

    # 6. Comprobar fechas
    if set(df_financiero["fecha"]) != set(df_cartera["fecha"]):
        raise ValueError(
            f"Las fechas no coinciden para {banco}"
        )

    # 7. Integrar
    resultado = df_financiero.merge(
        df_cartera,
        on="fecha",
        how="inner",
        validate="one_to_one"
    )

    # 8. Incorporar banco
    resultado.insert(1, "banco", banco)

    # 9. Ordenar
    resultado = (
        resultado
        .sort_values("fecha")
        .reset_index(drop=True)
    )

    return resultado

In [41]:
# Archivos históricos
archivos_prueba = [
    SERIES_DIR / "BP GUAYAQUIL 2026_09.xlsx",
    SERIES_DIR / "BP DINERS 2026_09.xlsx"
]

# Extraer series
series_adicionales = []

for archivo in archivos_prueba:

    df = extraer_serie_banco(archivo)

    series_adicionales.append(df)

    print(f"\nBanco: {df['banco'].iloc[0]}")
    print("Observaciones:", len(df))
    print("Inicio:", df["fecha"].min())
    print("Fin:", df["fecha"].max())

    print("\nValores faltantes:")
    print(df.isna().sum())

Banco: BP GUAYAQUIL
Observaciones: 285
Inicio: 2003-01-01 00:00:00
Fin: 2026-09-01 00:00:00

Valores faltantes:
fecha                   0
banco                   0
solvencia               1
liquidez                0
roa                     0
roe                     0
cartera_depositos       0
cartera_bruta           0
cartera_improductiva    0
morosidad_total         0
cobertura               0
dtype: int64

Banco: BP DINERS
Observaciones: 112
Inicio: 2017-06-01 00:00:00
Fin: 2026-09-01 00:00:00

Valores faltantes:
fecha                   0
banco                   0
solvencia               1
liquidez                0
roa                     0
roe                     0
cartera_depositos       0
cartera_bruta           0
cartera_improductiva    0
morosidad_total         0
cobertura               0
dtype: int64

In [42]:
# Integrar las tres instituciones
panel_prueba = pd.concat(
    [serie_bp_2026] + series_adicionales,
    ignore_index=True
)

# Ordenar
panel_prueba = (
    panel_prueba
    .sort_values(["banco", "fecha"])
    .reset_index(drop=True)
)

# Comprobar dimensiones
print("Dimensiones:", panel_prueba.shape)

# Resumen por institución
resumen = (
    panel_prueba
    .groupby("banco")
    .agg(
        inicio=("fecha", "min"),
        fin=("fecha", "max"),
        meses=("fecha", "count"),
        morosidad_promedio=("morosidad_total", "mean")
    )
)

display(resumen)

# Verificar duplicados
print(
    "\nDuplicados banco-mes:",
    panel_prueba.duplicated(
        subset=["banco", "fecha"]
    ).sum()
)

Dimensiones: (682, 11)

                 inicio        fin  meses  morosidad_promedio
banco
BP DINERS    2017-06-01 2026-09-01    112            0.049149
BP GUAYAQUIL 2003-01-01 2026-09-01    285            0.027854
BP PICHINCHA 2003-01-01 2026-09-01    285            0.041310

Duplicados banco-mes: 0

In [5]:
# Cargar el boletín de Delbank
archivo = SERIES_DIR / "BP DELBANK 2026_09.xlsx"

delbank = pd.read_excel(
    archivo,
    sheet_name="INDIC CARTERA",
    header=None
)

# Extraer fechas
fechas = pd.to_datetime(
    delbank.iloc[4, 3:],
    errors="coerce"
).dropna()

columnas = fechas.index

# Construir una tabla de diagnóstico
diagnostico = pd.DataFrame({
    "fecha": fechas.to_numpy(),

    "cartera_bruta": pd.to_numeric(
        delbank.loc[18, columnas],
        errors="coerce"
    ).to_numpy(),

    "cartera_improductiva": pd.to_numeric(
        delbank.loc[40, columnas],
        errors="coerce"
    ).to_numpy(),

    "morosidad_total": pd.to_numeric(
        delbank.loc[92, columnas],
        errors="coerce"
    ).to_numpy()
})

# Identificar saldos de cartera bruta no positivos
anomalias = diagnostico.loc[
    diagnostico["cartera_bruta"] <= 0
]

print("Registros con cartera bruta no positiva:", len(anomalias))

display(anomalias)

Registros con cartera bruta no positiva: 6

       fecha  cartera_bruta  cartera_improductiva  morosidad_total
0 2003-11-30            0.0                   0.0              0.0
1 2003-12-31            0.0                   0.0              0.0
2 2004-01-31            0.0                   0.0              0.0
3 2004-02-29            0.0                   0.0              0.0
4 2004-03-31            0.0                   0.0              0.0
6 2004-05-31            0.0                   0.0              0.0

In [10]:
# Inspeccionar los meses cercanos a la anomalía

periodo = diagnostico[
    diagnostico["fecha"].between(
        "2003-10-01",
        "2004-06-30"
    )
]

display(periodo)

       fecha  cartera_bruta  cartera_improductiva  morosidad_total
0 2003-11-30           0.00                   0.0              0.0
1 2003-12-31           0.00                   0.0              0.0
2 2004-01-31           0.00                   0.0              0.0
3 2004-02-29           0.00                   0.0              0.0
4 2004-03-31           0.00                   0.0              0.0
5 2004-04-30           0.01                   0.0              0.0
6 2004-05-31           0.00                   0.0              0.0
7 2004-06-30           3.00                   0.0              0.0

### Probar el modulo de extraccion

In [2]:
import sys

# Incorporar la raíz del proyecto a las rutas de Python
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Importar nuestras funciones
from src.boletines import (
    extraer_serie_banco,
    validar_serie,
    construir_panel
)

In [3]:
# Directorio de series históricas
SERIES_DIR = PROJECT_ROOT / "data" / "raw" / "series_entidad"

# Procesar automáticamente los boletines
panel_bancario, reporte_calidad = construir_panel(
    directorio=SERIES_DIR,
    patron="*2026_09.xlsx"
)

print("Dimensiones del panel:", panel_bancario.shape)

print("\nReporte de calidad:")
display(reporte_calidad)

print("\nPrimeras observaciones:")
display(panel_bancario.head())

/home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador/src/boletines.py:234: RuntimeWarning: BP DELBANK: 6 mes(es) con cartera bruta <= 0 y 0 mes(es) con cartera improductiva < 0. Períodos afectados: 2003-11, 2003-12, 2004-01, 2004-02, 2004-03, 2004-05. Se marcan como NaN los saldos inválidos y la morosidad de esos meses; deben revisarse contra el archivo original.
  serie = _limpiar_saldos_invalidos(serie)

Dimensiones del panel: (5972, 11)

Reporte de calidad:

,archivo,banco,inicio,fin,meses,faltantes_solvencia,faltantes_cartera_bruta,faltantes_cartera_improductiva,faltantes_morosidad,meses_morosidad_verificables,meses_morosidad_no_verificables,diferencia_maxima_morosidad
0,BANCO ATLANTIDA S.A. 2026_09.xlsx,BANCO ATLANTIDA S.A.,2011-07-01,2026-09-01,183,2,0,0,0,183,0,4.928322e-11
1,BP COMERCIAL DE MANABI 2026_09.xlsx,BANCO COMERCIAL DE MANABI,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.997592e-11
2,BP AMAZONAS 2026_09.xlsx,BP AMAZONAS,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.985783e-11
3,BP AUSTRO 2026_09.xlsx,BP AUSTRO,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.994963e-11
4,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...","BP BANCO DESARROLLO DE LOS PUEBLOS S.A., CODES...",2014-03-01,2026-09-01,151,1,0,0,0,151,0,4.985336e-11
5,BP BOLIVARIANO 2026_09.xlsx,BP BOLIVARIANO,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.986012e-11
6,BP CAPITAL 2026_09.xlsx,BP CAPITAL,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.994244e-11
7,BP CITIBANK 2026_09.xlsx,BP CITIBANK,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.999047e-11
8,BP COOPNACIONAL 2026_09.xlsx,BP COOPNACIONAL,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.922054e-11
9,BP DELBANK 2026_09.xlsx,BP DELBANK,2003-11-01,2026-09-01,275,8,6,0,6,269,6,4.980659e-11
10,BP DINERS 2026_09.xlsx,BP DINERS,2017-06-01,2026-09-01,112,1,0,0,0,112,0,4.800041e-11
11,BP GENERAL RUMIÑAHUI 2026_09.xlsx,BP GENERAL RUMINAHUI,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.997432e-11
12,BP GUAYAQUIL 2026_09.xlsx,BP GUAYAQUIL,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.998968e-11
13,BP INTERNACIONAL 2026_09.xlsx,BP INTERNACIONAL,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.987750e-11
14,BP LITORAL 2026_09.xlsx,BP LITORAL,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.986983e-11
15,BP LOJA 2026_09.xlsx,BP LOJA,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.990972e-11
16,BP MACHALA 2026_09.xlsx,BP MACHALA,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.982918e-11
17,BP PACIFICO 2026_09.xlsx,BP PACIFICO,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.993349e-11
18,BP PICHINCHA 2026_09.xlsx,BP PICHINCHA,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.988563e-11
19,BP PROCREDIT 2026_09.xlsx,BP PROCREDIT,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.971816e-11
20,BP PRODUBANCO 2026_09.xlsx,BP PRODUBANCO,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.985786e-11
21,BP SOLIDARIO 2026_09.xlsx,BP SOLIDARIO,2003-01-01,2026-09-01,285,1,0,0,0,285,0,4.987753e-11
22,BP VISIONFUND ECUADOR S.A. 2026_09.xlsx,BP VISIONFUND ECUADOR S.A.,2016-09-01,2026-09-01,121,1,0,0,0,121,0,4.935093e-11

Primeras observaciones:

,fecha,banco,solvencia,liquidez,roa,roe,cartera_depositos,cartera_bruta,cartera_improductiva,morosidad_total,cobertura
0,2011-07-01,BANCO ATLANTIDA S.A.,NaN,0.0,0.019541,0.091531,0.0,31872.72431,828.74366,0.026002,0.776931
1,2011-08-01,BANCO ATLANTIDA S.A.,0.25177,0.0,0.018258,0.085764,0.0,33162.49816,728.98974,0.021982,1.002009
2,2011-09-01,BANCO ATLANTIDA S.A.,0.28814,0.0,0.017008,0.081672,0.0,34827.65249,822.65943,0.023621,1.003828
3,2011-10-01,BANCO ATLANTIDA S.A.,0.26950,0.0,0.016025,0.073058,0.0,36890.47681,909.87157,0.024664,1.026205
4,2011-11-01,BANCO ATLANTIDA S.A.,0.26057,0.0,0.015737,0.070117,0.0,38955.55403,1020.61617,0.026200,1.007305

In [4]:
# Crear directorio si no existe
INTERIM_DIR = PROJECT_ROOT / "data" / "interim"
INTERIM_DIR.mkdir(parents=True, exist_ok=True)

# Guardar panel preliminar
panel_bancario.to_csv(
    INTERIM_DIR / "panel_bancario_piloto_2026_09.csv",
    index=False
)

# Guardar reporte de calidad
reporte_calidad.to_csv(
    INTERIM_DIR / "reporte_calidad_piloto_2026_09.csv",
    index=False
)

print("Archivos guardados correctamente.")

Archivos guardados correctamente.

In [5]:
# Variables financieras que queremos analizar
variables = [
    "solvencia",
    "liquidez",
    "roa",
    "roe",
    "cartera_depositos",
    "cartera_bruta",
    "cartera_improductiva",
    "morosidad_total",
    "cobertura"
]

# Contar ceros por institución y variable
resumen_ceros = (
    panel_bancario
    .groupby("banco")[variables]
    .agg(lambda x: (x == 0).sum())
)

# Mostrar únicamente instituciones con al menos un cero
resumen_ceros = resumen_ceros.loc[
    resumen_ceros.sum(axis=1) > 0
]

display(resumen_ceros)

,solvencia,liquidez,roa,roe,cartera_depositos,cartera_bruta,cartera_improductiva,morosidad_total,cobertura
banco,,,,,,,,,
BANCO ATLANTIDA S.A.,0,8,0,0,6,0,0,0,0
BP DELBANK,0,5,5,5,6,0,18,12,18

In [6]:
# Instituciones con valores iguales a cero
bancos_revision = [
    "BANCO ATLANTIDA S.A.",
    "BP DELBANK"
]

# Variables que requieren revisión
variables_revision = [
    "liquidez",
    "roa",
    "roe",
    "cartera_depositos",
    "cartera_improductiva",
    "morosidad_total",
    "cobertura"
]

for banco in bancos_revision:

    df_banco = panel_bancario.loc[
        panel_bancario["banco"] == banco
    ].copy()

    print(f"\n{'=' * 60}")
    print(f"BANCO: {banco}")
    print(f"{'=' * 60}")

    for variable in variables_revision:

        fechas = (
            df_banco.loc[
                df_banco[variable] == 0,
                "fecha"
            ]
            .dt.strftime("%Y-%m")
            .tolist()
        )

        if fechas:
            print(f"\n{variable}: {len(fechas)} ceros")
            print(fechas)

============================================================
BANCO: BANCO ATLANTIDA S.A.
============================================================

liquidez: 8 ceros
['2011-07', '2011-08', '2011-09', '2011-10', '2011-11', '2011-12', '2012-01', '2012-02']

cartera_depositos: 6 ceros
['2011-07', '2011-08', '2011-09', '2011-10', '2011-11', '2011-12']

============================================================
BANCO: BP DELBANK
============================================================

liquidez: 5 ceros
['2003-11', '2003-12', '2004-01', '2004-02', '2004-03']

roa: 5 ceros
['2003-11', '2003-12', '2004-01', '2004-02', '2004-03']

roe: 5 ceros
['2003-11', '2003-12', '2004-01', '2004-02', '2004-03']

cartera_depositos: 6 ceros
['2003-11', '2003-12', '2004-01', '2004-02', '2004-03', '2004-05']

cartera_improductiva: 18 ceros
['2003-11', '2003-12', '2004-01', '2004-02', '2004-03', '2004-04', '2004-05', '2004-06', '2004-07', '2004-08', '2004-09', '2004-10', '2004-11', '2004-12', '2005-01', '2005-02', '2005-03', '2005-04']

morosidad_total: 12 ceros
['2004-04', '2004-06', '2004-07', '2004-08', '2004-09', '2004-10', '2004-11', '2004-12', '2005-01', '2005-02', '2005-03', '2005-04']

cobertura: 18 ceros
['2003-11', '2003-12', '2004-01', '2004-02', '2004-03', '2004-04', '2004-05', '2004-06', '2004-07', '2004-08', '2004-09', '2004-10', '2004-11', '2004-12', '2005-01', '2005-02', '2005-03', '2005-04']

In [7]:
# Seleccionar Delbank
delbank = panel_bancario.loc[
    panel_bancario["banco"] == "BP DELBANK"
].copy()

# Seleccionar meses con cartera improductiva igual a cero
delbank_ceros = delbank.loc[
    delbank["cartera_improductiva"] == 0,
    [
        "fecha",
        "cartera_bruta",
        "cartera_improductiva",
        "morosidad_total",
        "cobertura"
    ]
]

print("Meses con cartera improductiva = 0:")
print(len(delbank_ceros))

display(delbank_ceros)

# Comprobar consistencia
print("\nComprobaciones:")

print(
    "Cartera bruta positiva:",
    (delbank_ceros["cartera_bruta"] > 0).sum()
)

print(
    "Cartera bruta faltante:",
    delbank_ceros["cartera_bruta"].isna().sum()
)

print(
    "Morosidad igual a cero:",
    (delbank_ceros["morosidad_total"] == 0).sum()
)

print(
    "Morosidad faltante:",
    delbank_ceros["morosidad_total"].isna().sum()
)

print(
    "Cobertura igual a cero:",
    (delbank_ceros["cobertura"] == 0).sum()
)

Meses con cartera improductiva = 0:
18

,fecha,cartera_bruta,cartera_improductiva,morosidad_total,cobertura
2329,2003-11-01,NaN,0.0,NaN,0.0
2330,2003-12-01,NaN,0.0,NaN,0.0
2331,2004-01-01,NaN,0.0,NaN,0.0
2332,2004-02-01,NaN,0.0,NaN,0.0
2333,2004-03-01,NaN,0.0,NaN,0.0
2334,2004-04-01,0.01000,0.0,0.0,0.0
2335,2004-05-01,NaN,0.0,NaN,0.0
2336,2004-06-01,3.00000,0.0,0.0,0.0
2337,2004-07-01,4.60960,0.0,0.0,0.0
2338,2004-08-01,9.23081,0.0,0.0,0.0
2339,2004-09-01,25.01691,0.0,0.0,0.0
2340,2004-10-01,25.42791,0.0,0.0,0.0
2341,2004-11-01,24.79100,0.0,0.0,0.0
2342,2004-12-01,22.95124,0.0,0.0,0.0
2343,2005-01-01,26.44860,0.0,0.0,0.0
2344,2005-02-01,27.06234,0.0,0.0,0.0
2345,2005-03-01,44.80940,0.0,0.0,0.0
2346,2005-04-01,77.29171,0.0,0.0,0.0

Comprobaciones:
Cartera bruta positiva: 12
Cartera bruta faltante: 6
Morosidad igual a cero: 12
Morosidad faltante: 6
Cobertura igual a cero: 18

In [1]:
import importlib
import src.boletines as boletines

# Recargar el módulo
importlib.reload(boletines)

# Reconstruir panel
panel_bancario, reporte_calidad = boletines.construir_panel(
    directorio=SERIES_DIR,
    patron="*2026_09.xlsx"
)

print("Dimensiones:", panel_bancario.shape)
print("Instituciones:", panel_bancario["banco"].nunique())

display(reporte_calidad)

ModuleNotFoundError: No module named 'src'

In [9]:
# Seleccionar Delbank
delbank = panel_bancario.loc[
    panel_bancario["banco"] == "BP DELBANK"
]

print("VALIDACIÓN FINAL: DELBANK")

print(
    "Cartera bruta faltante:",
    delbank["cartera_bruta"].isna().sum()
)

print(
    "Cartera improductiva igual a cero:",
    (delbank["cartera_improductiva"] == 0).sum()
)

print(
    "Morosidad igual a cero:",
    (delbank["morosidad_total"] == 0).sum()
)

print(
    "Morosidad faltante:",
    delbank["morosidad_total"].isna().sum()
)

print(
    "Cobertura faltante:",
    delbank["cobertura"].isna().sum()
)

# Verificar consistencia del tratamiento
assert delbank.loc[
    delbank["cartera_improductiva"] == 0,
    "cobertura"
].isna().all()

print("\nTratamiento de cobertura validado.")

VALIDACIÓN FINAL: DELBANK
Cartera bruta faltante: 6
Cartera improductiva igual a cero: 18
Morosidad igual a cero: 12
Morosidad faltante: 6
Cobertura faltante: 18

Tratamiento de cobertura validado.

In [10]:
# Directorio de datos intermedios
INTERIM_DIR = PROJECT_ROOT / "data" / "interim"
INTERIM_DIR.mkdir(parents=True, exist_ok=True)

# Guardar panel
panel_bancario.to_parquet(
    INTERIM_DIR / "panel_bancario_2026_09.parquet",
    index=False
)

# Guardar reporte de calidad
reporte_calidad.to_csv(
    INTERIM_DIR / "reporte_calidad_2026_09.csv",
    index=False
)

print("Datos intermedios guardados correctamente.")

ArrowKeyError: No type extension with name arrow.py_extension_type found