## Validacion de Datos de bancos

In [8]:
from pathlib import Path
import pandas as pd

# Directorio de datos originales
RAW_DIR = Path("data/raw")

# Archivos disponibles
archivo_2009 = "/home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador/data/raw/boletin_mensual/BOL_FIN_BCOS_SEP_09 A.xls"

archivo_2014 = "/home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador/data/raw/cartera_deposito/BANCOS PRIVADOS COLOCACIONES - CONSUMO ENE-DIC 2014.xlsx"

# Abrir los libros
excel_2014 = pd.ExcelFile(archivo_2014)
excel_2009 = pd.ExcelFile(archivo_2009)

print("Hojas del archivo 2014:")
print(excel_2014.sheet_names)

print("\nHojas del archivo 2009:")
print(excel_2009.sheet_names)

Hojas del archivo 2014:
['BANCOS PRIVADOS CONSUMO']

Hojas del archivo 2009:
['BAL SAB II', 'EPyG SAB II', 'CONSCOND', 'BALCONS', 'BALCONS %', 'GRAFICOS', 'RK ', 'GRAF RK', 'COMPOS CART', 'COMPOS CART %', 'CAPCOL x PLAZOS', 'EPyG', 'EPyG %', 'INDIC', 'CARTxPLAZ']

In [9]:
# Cargar indicadores financieros
indicadores = pd.read_excel(
    excel_2009,
    sheet_name="INDIC",
    header=None
)

# Cargar composición de cartera
cartera = pd.read_excel(
    excel_2009,
    sheet_name="COMPOS CART",
    header=None
)

print("Dimensiones de INDIC:", indicadores.shape)
print("Dimensiones de COMPOS CART:", cartera.shape)

display(indicadores.iloc[18:31, :10])

Dimensiones de INDIC: (102, 36)
Dimensiones de COMPOS CART: (75, 36)

,0,1,2,3,4,5,6,7,8,9
18,NaN,NaN,INDICES DE MOROSIDAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,IF28,MOROSIDAD DE LA CARTERA DE CREDITOS COMERCIALES,1.549464,5.839114,2.656962,0.466369,2.376627,8.392526,0.818966
20,NaN,IF29,MOROSIDAD DE LA CARTERA DE CREDITOS DE CONSUMO,3.90864,2.888954,5.495679,4.419331,4.388588,9.163498,4.405068
21,NaN,IF30,MOROSIDAD DE LA CARTERA DE CREDITOS DE VIVIENDA,0.771935,1.148377,1.418651,1.888276,1.311159,2.109428,3.868015
22,NaN,IF31,MOROSIDAD DE LA CARTERA DE CREDITOS PARA LA MI...,0,3.43487,3.465278,5.085958,3.478514,3.521004,0
23,NaN,NaN,MOROSIDAD DE LA CARTERA TOTAL,2.820326,3.693786,3.294239,1.19638,2.99347,8.42018,1.677995
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,COBERTURA DE PROVISIONES PARA CARTERA IMPRODUC...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,COBERTURA DE LA CARTERA COMERCIAL,188.852782,515.580491,488.319301,554.523234,470.421004,64.998244,422.970828
27,NaN,NaN,COBERTURA DE LA CARTERA DE CONSUMO,72.842168,99.655064,183.699694,67.668463,133.687948,78.084465,74.07784
28,NaN,NaN,COBERTURA DE LA CARTERA DE VIVIENDA,146.214011,113.751471,479.322226,134.396515,389.965473,67.720765,38.386609
29,NaN,NaN,COBERTURA DE LA CARTERA DE MICROEMPRESA,0,174.789635,259.74061,98.343776,257.655497,60.105833,0
30,NaN,NaN,COBERTURA DE LA CARTERA PROBLEMÁTICA,95.22804,338.884757,313.744614,222.386722,272.709824,73.034907,195.564502

In [26]:
indicadores.head()

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,INDICADORES FINANCIEROS DEL SISTEMA DE SOCIEDA...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,2009-09-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,(en porcentajes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# Inspeccionar las primeras filas para localizar los nombres de bancos

display(
    indicadores.iloc[:12, :15].T
)

,0,1,2,3,4,5,6,7,8,9,10,11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COD. MAF.,NaN,NaN,IF114,NaN
2,NaN,INDICADORES FINANCIEROS DEL SISTEMA DE SOCIEDA...,SISTEMA DE BANCOS PRIVADOS,2009-09-30 00:00:00,(en porcentajes),NaN,NaN,NOMBRE DEL INDICADOR,NaN,SUFICIENCIA PATRIMONIAL,( PATRIMONIO +RESULTADOS ) / ACTIVOS INMOVILIZ...,PATRIMONIO / ACTIVOS INMOVILIZADOS (DIC)
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP GUAYAQUIL,NaN,NaN,97.032477,84.093205
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP PACIFICO,NaN,NaN,533.241368,486.255184
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP PICHINCHA,NaN,NaN,1028.017957,938.788205
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP PRODUBANCO,NaN,NaN,255.001819,234.313168
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BANCOS PRIVADOS GRANDES,NaN,NaN,312.60064,283.162813
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP AUSTRO,NaN,NaN,138.192333,118.83227
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP BOLIVARIANO,NaN,NaN,210.249821,189.815884
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP GENERAL RUMIÑAHUI,NaN,NaN,350.546244,306.901618
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP INTERNACIONAL,NaN,NaN,219.079344,202.679892
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP MACHALA,NaN,NaN,141.507377,133.433988
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BP PROMERICA,NaN,NaN,134.891136,128.585359
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BANCOS PRIVADOS MEDIANOS,NaN,NaN,184.926784,168.07207

catalogo de instituciones

In [23]:
# Extraer nombres de las instituciones financieras
nombres = (
    indicadores.iloc[7, 3:]
    .dropna()
    .astype(str)
    .str.strip()
)

# Construir catálogo de instituciones
catalogo = pd.DataFrame({
    "columna_original": nombres.index,
    "institucion": nombres.values
})

# Clasificar instituciones y agregados
catalogo["tipo"] = catalogo["institucion"].apply(
    lambda x: "Banco" if x.startswith("BP ") else "Agregado"
)

# Visualizar catálogo
display(catalogo)

# Contar registros según clasificación
print("\nResumen:")
print(catalogo["tipo"].value_counts())

    columna_original                      institucion      tipo
0                  3                     BP GUAYAQUIL     Banco
1                  4                      BP PACIFICO     Banco
2                  5                     BP PICHINCHA     Banco
3                  6                    BP PRODUBANCO     Banco
4                  7          BANCOS PRIVADOS GRANDES  Agregado
5                  8                        BP AUSTRO     Banco
6                  9                   BP BOLIVARIANO     Banco
7                 10             BP GENERAL RUMIÑAHUI     Banco
8                 11                 BP INTERNACIONAL     Banco
9                 12                       BP MACHALA     Banco
10                13                     BP PROMERICA     Banco
11                14         BANCOS PRIVADOS MEDIANOS  Agregado
12                15                      BP AMAZONAS     Banco
13                16                      BP CITIBANK     Banco
14                17                        BP COFIEC     Banco
15                18           BP COMERCIAL DE MANABI     Banco
16                19                       BP LITORAL     Banco
17                20                   BP LLOYDS BANK     Banco
18                21                          BP LOJA     Banco
19                22                     BP SOLIDARIO     Banco
20                23                  BP SUDAMERICANO     Banco
21                24                   BP TERRITORIAL     Banco
22                25                      BP UNIBANCO     Banco
23                26                     BP PROCREDIT     Banco
24                27                       BP CAPITAL     Banco
25                28                         BP FINCA     Banco
26                29                       BP DELBANK     Banco
27                30         BANCOS PRIVADOS PEQUEÑOS  Agregado
28                31            TOTAL BANCOS PRIVADOS  Agregado
29                32      BANCOS PRIVADOS COMERCIALES  Agregado
30                33          BANCOS PRIVADOS CONSUMO  Agregado
31                34         BANCOS PRIVADOS VIVIENDA  Agregado
32                35  BANCOS PRIVADOS DE MICROEMPRESA  Agregado

Resumen:
tipo
Banco       25
Agregado     8
Name: count, dtype: int64

In [28]:
# 1. Seleccionar únicamente bancos individuales

bancos = catalogo.loc[
    catalogo["tipo"] == "Banco",
    ["columna_original", "institucion"]
].copy()

# 2. Identificar las filas de los indicadores financieros

filas_indicadores = {
    "morosidad_comercial": 19,
    "morosidad_consumo": 20,
    "morosidad_vivienda": 21,
    "morosidad_microempresa": 22,
    "morosidad_total": 23,
    "cobertura_cartera_problematica": 30
}

# 3. Obtener las columnas correspondientes a bancos

columnas_bancos = bancos["columna_original"].tolist()

# 4. Extraer los valores de cada indicador

for variable, fila in filas_indicadores.items():

    valores = indicadores.iloc[fila, columnas_bancos]

    bancos[variable] = pd.to_numeric(
        valores,
        errors="coerce"
    ).to_numpy()

# 5. Extraer la fecha del boletín financiero

fecha = pd.to_datetime(indicadores.iloc[3, 2])

# Normalizar al primer día del mes
fecha = fecha.to_period("M").to_timestamp()

# 6. Organizar nuestro DataFrame

bancos.insert(0, "fecha", fecha)

bancos = bancos.rename(
    columns={"institucion": "banco"}
)

bancos = bancos.drop(
    columns="columna_original"
)

# 7. Reiniciar los índices

bancos = bancos.reset_index(drop=True)

# 8. Visualizar resultados

display(bancos.head(10))

,fecha,banco,morosidad_comercial,morosidad_consumo,morosidad_vivienda,morosidad_microempresa,morosidad_total,cobertura_cartera_problematica
0,2009-09-01,BP GUAYAQUIL,1.549464,3.908640,0.771935,0.000000,2.820326,95.228040
1,2009-09-01,BP PACIFICO,5.839114,2.888954,1.148377,3.434870,3.693786,338.884757
2,2009-09-01,BP PICHINCHA,2.656962,5.495679,1.418651,3.465278,3.294239,313.744614
3,2009-09-01,BP PRODUBANCO,0.466369,4.419331,1.888276,5.085958,1.196380,222.386722
4,2009-09-01,BP AUSTRO,8.392526,9.163498,2.109428,3.521004,8.420180,73.034907
5,2009-09-01,BP BOLIVARIANO,0.818966,4.405068,3.868015,0.000000,1.677995,195.564502
6,2009-09-01,BP GENERAL RUMIÑAHUI,4.777030,3.353731,5.799863,7.101269,4.523603,120.612777
7,2009-09-01,BP INTERNACIONAL,2.838455,5.177875,1.672050,2.486715,2.758083,101.608081
8,2009-09-01,BP MACHALA,2.012111,5.708310,0.534063,5.579913,3.381360,97.527750
9,2009-09-01,BP PROMERICA,1.542533,7.944056,2.341652,6.308981,2.936572,96.022393

In [29]:
# Dimensiones del dataset
print("Dimensiones:", bancos.shape)

# Tipos de datos
print("\nTipos de datos:")
print(bancos.dtypes)

# Valores faltantes
print("\nValores faltantes:")
print(bancos.isna().sum())

# Registros duplicados por banco y fecha
print("\nDuplicados:")
print(bancos.duplicated(
    subset=["fecha", "banco"]
).sum())

# Comprobar el indicador de Banco Pichincha
print("\nIndicadores de Banco Pichincha:")

display(
    bancos.loc[
        bancos["banco"] == "BP PICHINCHA"
    ]
)

Dimensiones: (25, 8)

Tipos de datos:
fecha                             datetime64[us]
banco                                        str
morosidad_comercial                      float64
morosidad_consumo                        float64
morosidad_vivienda                       float64
morosidad_microempresa                   float64
morosidad_total                          float64
cobertura_cartera_problematica           float64
dtype: object

Valores faltantes:
fecha                             0
banco                             0
morosidad_comercial               0
morosidad_consumo                 0
morosidad_vivienda                0
morosidad_microempresa            0
morosidad_total                   0
cobertura_cartera_problematica    0
dtype: int64

Duplicados:
0

Indicadores de Banco Pichincha:

,fecha,banco,morosidad_comercial,morosidad_consumo,morosidad_vivienda,morosidad_microempresa,morosidad_total,cobertura_cartera_problematica
2,2009-09-01,BP PICHINCHA,2.656962,5.495679,1.418651,3.465278,3.294239,313.744614

### inspeccionar Compos cart

In [30]:
# Dimensiones de la hoja
print("Dimensiones:", cartera.shape)

# Inspeccionar encabezados y primeras filas
display(cartera.iloc[:16, :10])

# Buscar filas relacionadas con cartera bruta e improductiva
patron = r"CARTERA BRUTA|CARTERA IMPRODUCTIVA"

etiquetas = cartera.iloc[:, :4].astype("string")

filas = etiquetas.apply(
    lambda columna: columna.str.contains(
        patron,
        case=False,
        regex=True,
        na=False
    )
).any(axis=1)

display(cartera.loc[filas].iloc[:, :10])

Dimensiones: (75, 36)

,0,1,2,3,4,5,6,7,8,9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,COMPOSICION DE LA CARTERA DE CREDITOS POR VENC...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,SISTEMA DE BANCOS PRIVADOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2009-09-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,(en miles de dólares),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,CODIGO,CUENTA,BP GUAYAQUIL,BP PACIFICO,BP PICHINCHA,BP PRODUBANCO,BANCOS PRIVADOS GRANDES,BP AUSTRO,BP BOLIVARIANO
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,CARTERA BRUTA,1077079.2414,805819.84665,2836288.9457,684945.34512,5404133.37887,375572.32918,634708.27396
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,1401,CARTERA DE CREDITOS COMERCIAL POR VENCER,336189.26948,255867.29377,1024282.56333,535166.38669,2151505.51327,126651.82277,471712.58562
11,NaN,1402,CARTERA DE CREDITOS DE CONSUMO POR VENCER,594544.58302,378514.82888,749516.7896,105930.31298,1828506.51448,191804.26022,105873.97288
12,NaN,1403,CARTERA DE CREDITOS DE VIVIENDA POR VENCER,115968.24505,121471.29065,592791.33369,30672.66838,860903.53777,20513.84478,45319.81458
13,NaN,1404,CARTERA DE CREDITOS PARA LA MICROEMPRESA POR V...,0,523.2808,360319.46221,2934.48016,363777.22317,4125.84715,0
14,NaN,1405,CARTERA DE CREDITOS COMERCIAL REESTRUCTURADA P...,0,19371.69274,15052.56021,973.38733,35397.64028,459.04801,0
15,NaN,1406,CARTERA DE CREDITOS DE CONSUMO REESTRUCTURADA ...,0,16.85454,33.84317,605.45775,656.15546,360.52658,1151.52758

,0,1,2,3,4,5,6,7,8,9
8,NaN,NaN,CARTERA BRUTA,1077079.2414,805819.84665,2836288.9457,684945.34512,5404133.37887,375572.32918,634708.27396
49,NaN,NaN,CARTERA IMPRODUCTIVA COMERCIAL,5291.11438,17068.14682,28368.47634,2512.10353,53239.84107,11645.13416,3895.06725
50,NaN,NaN,CARTERA IMPRODUCTIVA CONSUMO,24183.86591,11260.92953,43588.37459,4925.85811,83959.02814,19385.39727,4931.79498
51,NaN,NaN,CARTERA IMPRODUCTIVA VIVIENDA,902.16356,1413.03222,8543.01286,599.34086,11457.5495,442.76297,1823.51107
52,NaN,NaN,CARTERA IMPRODUCTIVA MICROEMPRESA,0,23.15385,12934.27862,157.24379,13114.67626,150.57294,0
53,NaN,NaN,TOTAL CARTERA IMPRODUCTIVA (NO DEVENGA INTERE...,30377.14385,29765.26242,93434.14241,8194.54629,161771.09497,31623.86734,10650.3733
55,NaN,NaN,CARTERA BRUTA COMERCIAL,341480.38386,292307.13333,1067703.59988,538651.87755,2240142.99462,138756.00494,475607.65287
56,NaN,NaN,CARTERA BRUTA CONSUMO,618728.44893,389792.61295,793139.00736,111461.62884,1913121.69808,211550.18407,111957.29544
57,NaN,NaN,CARTERA BRUTA VIVIENDA,116870.40861,123046.01816,602192.59763,31740.11478,873849.13918,20989.72008,47143.32565
58,NaN,NaN,CARTERA BRUTA MICROEMPRESA,0,674.08221,373253.74083,3091.72395,377019.54699,4276.42009,0
59,NaN,NaN,TOTAL CARTERA BRUTA,1077079.2414,805819.84665,2836288.9457,684945.34512,5404133.37887,375572.32918,634708.27396

In [36]:
# 1. Obtener los nombres de las instituciones en COMPOS CART

nombres_cartera = (
    cartera.iloc[6, 3:]
    .dropna()
    .astype(str)
    .str.strip()
)

# Conservar solamente los bancos individuales
nombres_cartera = nombres_cartera[
    nombres_cartera.str.startswith("BP ")
]

# 2. Identificar sus columnas originales

columnas = nombres_cartera.index

# 3. Extraer los saldos financieros

saldos = pd.DataFrame({
    "banco": nombres_cartera.values,

    "cartera_bruta": pd.to_numeric(
        cartera.loc[59, columnas],
        errors="coerce"
    ).to_numpy(),

    "cartera_improductiva": pd.to_numeric(
        cartera.loc[53, columnas],
        errors="coerce"
    ).to_numpy()
})

# 4. Calcular la morosidad

denominador = saldos["cartera_bruta"].where(
    saldos["cartera_bruta"] > 0
)

saldos["morosidad_calculada"] = (
    saldos["cartera_improductiva"] / denominador
) * 100

# 5. Comparar con la morosidad publicada en INDIC

validacion = bancos[
    ["banco", "morosidad_total"]
].merge(
    saldos,
    on="banco",
    how="left",
    validate="one_to_one"
)

# 6. Calcular diferencia absoluta en puntos porcentuales

validacion["diferencia_pp"] = (
    validacion["morosidad_total"]
    - validacion["morosidad_calculada"]
).abs()

# 7. Mostrar resultados

display(validacion)

,banco,morosidad_total,cartera_bruta,cartera_improductiva,morosidad_calculada,diferencia_pp
0,BP GUAYAQUIL,2.820326,1.077079e+06,30377.14385,2.820326,0.0
1,BP PACIFICO,3.693786,8.058198e+05,29765.26242,3.693786,0.0
2,BP PICHINCHA,3.294239,2.836289e+06,93434.14241,3.294239,0.0
3,BP PRODUBANCO,1.196380,6.849453e+05,8194.54629,1.196380,0.0
4,BP AUSTRO,8.420180,3.755723e+05,31623.86734,8.420180,0.0
5,BP BOLIVARIANO,1.677995,6.347083e+05,10650.37330,1.677995,0.0
6,BP GENERAL RUMIÑAHUI,4.523603,1.986914e+05,8988.00886,4.523603,0.0
7,BP INTERNACIONAL,2.758083,7.554464e+05,20835.83889,2.758083,0.0
8,BP MACHALA,3.381360,1.947916e+05,6586.60466,3.381360,0.0
9,BP PROMERICA,2.936572,2.585490e+05,7592.47698,2.936572,0.0
10,BP AMAZONAS,3.297416,5.914252e+04,1950.17491,3.297416,0.0
11,BP CITIBANK,0.021447,1.072435e+05,23.00000,0.021447,0.0
12,BP COFIEC,23.625000,7.281967e+03,1720.36477,23.625000,0.0
13,BP COMERCIAL DE MANABI,7.572641,1.385030e+04,1048.83351,7.572641,0.0
14,BP LITORAL,5.110259,1.056798e+04,540.05103,5.110259,0.0
15,BP LLOYDS BANK,0.002313,1.297128e+05,3.00000,0.002313,0.0
16,BP LOJA,3.586670,1.100782e+05,3948.14170,3.586670,0.0
17,BP SOLIDARIO,7.320684,2.218861e+05,16243.57826,7.320684,0.0
18,BP SUDAMERICANO,6.778027,2.625325e+03,177.94523,6.778027,0.0
19,BP TERRITORIAL,9.956624,8.274603e+04,8238.71033,9.956624,0.0
20,BP UNIBANCO,7.172645,1.594530e+05,11437.00000,7.172645,0.0
21,BP PROCREDIT,3.014568,2.275827e+05,6860.63689,3.014568,0.0
22,BP CAPITAL,10.404054,3.404995e+04,3542.57551,10.404054,0.0
23,BP FINCA,11.240542,2.587722e+04,2908.74000,11.240542,0.0
24,BP DELBANK,4.378598,7.719187e+03,337.99221,4.378598,0.0

In [37]:
# Tolerancia en puntos porcentuales
tolerancia = 0.0001

# Comprobar registros no verificables
no_verificables = validacion[
    validacion["morosidad_calculada"].isna()
]

# Identificar diferencias superiores a la tolerancia
diferencias = validacion[
    validacion["diferencia_pp"] > tolerancia
]

print("Total de bancos:", len(validacion))

print(
    "Bancos sin cálculo verificable:",
    len(no_verificables)
)

print(
    "Bancos con diferencias relevantes:",
    len(diferencias)
)

print(
    "Diferencia máxima:",
    validacion["diferencia_pp"].max()
)

# Mostrar los mayores errores
display(
    validacion.sort_values(
        "diferencia_pp",
        ascending=False
    ).head(10)
)

# Mostrar bancos que requieren revisión
if not no_verificables.empty or not diferencias.empty:
    display(
        validacion.loc[
            validacion["morosidad_calculada"].isna()
            | (validacion["diferencia_pp"] > tolerancia)
        ]
    )

Total de bancos: 25
Bancos sin cálculo verificable: 0
Bancos con diferencias relevantes: 0
Diferencia máxima: 0.0

,banco,morosidad_total,cartera_bruta,cartera_improductiva,morosidad_calculada,diferencia_pp
0,BP GUAYAQUIL,2.820326,1.077079e+06,30377.14385,2.820326,0.0
1,BP PACIFICO,3.693786,8.058198e+05,29765.26242,3.693786,0.0
2,BP PICHINCHA,3.294239,2.836289e+06,93434.14241,3.294239,0.0
3,BP PRODUBANCO,1.196380,6.849453e+05,8194.54629,1.196380,0.0
4,BP AUSTRO,8.420180,3.755723e+05,31623.86734,8.420180,0.0
5,BP BOLIVARIANO,1.677995,6.347083e+05,10650.37330,1.677995,0.0
6,BP GENERAL RUMIÑAHUI,4.523603,1.986914e+05,8988.00886,4.523603,0.0
7,BP INTERNACIONAL,2.758083,7.554464e+05,20835.83889,2.758083,0.0
8,BP MACHALA,3.381360,1.947916e+05,6586.60466,3.381360,0.0
9,BP PROMERICA,2.936572,2.585490e+05,7592.47698,2.936572,0.0

In [33]:
# Nombre registrado en INDIC
nombre_indic = bancos.loc[
    bancos["banco"].str.contains("GUAYAQUIL"),
    "banco"
].iloc[0]

# Nombre registrado en COMPOS CART
nombre_cartera = cartera.iloc[6, 4]

print("Nombre INDIC:")
print(repr(nombre_indic))

print("\nNombre COMPOS CART:")
print(repr(nombre_cartera))

print("\n¿Son iguales?")
print(nombre_indic == nombre_cartera)

print("\n¿Banco Guayaquil aparece en saldos?")
print(
    saldos["banco"].str.contains(
        "GUAYAQUIL",
        case=False,
        na=False
    ).any()
)

Nombre INDIC:
'BP GUAYAQUIL'

Nombre COMPOS CART:
'BP PACIFICO'

¿Son iguales?
False

¿Banco Guayaquil aparece en saldos?
False

In [34]:
import unicodedata


def normalizar_nombre(nombre):
    """Normaliza nombres de instituciones financieras."""

    nombre = unicodedata.normalize(
        "NFKC",
        str(nombre)
    )

    nombre = " ".join(nombre.upper().split())

    return nombre

In [35]:
print(normalizar_nombre("BP  GUAYAQUIL"))
print(normalizar_nombre(" BP GUAYAQUIL "))

BP GUAYAQUIL
BP GUAYAQUIL

## Series por banco

In [40]:
from pathlib import Path
import pandas as pd

# Directorio de series históricas
SERIES_DIR = Path("/home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador/data/raw/series_entidad/BP PICHINCHA DIC 2020 web.xlsx")

series_bp_2020 = "/home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador/data/raw/series_entidad/BP PICHINCHA DIC 2020 web.xlsx"

# Abrir el primer archivo
excel_historico = pd.ExcelFile(series_bp_2020)

print("\nHojas disponibles:")
for hoja in excel_historico.sheet_names:
    print(hoja)

Hojas disponibles:
BAL
PYG
BAL %
MET
GRUPOS CTAS
PYG SA
PYG %
INDIC CARTERA
GRAF CARTERA
INDICAD
BAL SM
VAR ABS BAL SM
FUENTES USOS
CAMEL
GRAF INDIC
ESTRUC CART
REFINA REES

In [41]:
# Examinar las primeras tres hojas

for hoja in excel_historico.sheet_names[:3]:

    df = pd.read_excel(
        excel_historico,
        sheet_name=hoja,
        header=None,
        nrows=12
    )

    print(f"\nHOJA: {hoja}")
    print(f"Dimensiones de la muestra: {df.shape}")

    display(df.iloc[:, :10])

HOJA: BAL
Dimensiones de la muestra: (12, 227)

,0,1,2,3,4,5,6,7,8,9
0,NaN,COMPARATIVO DE SITUACIÓN NOMINAL,NaN,0,0,0,0,0,0,-0.0
1,NaN,BP PICHINCHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,( en miles de dólares),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,7,8,9,10,11,12,1
4,NaN,CÓDIGO,CUENTA,2002-07-31 00:00:00,2002-08-31 00:00:00,2002-09-30 00:00:00,2002-10-31 00:00:00,2002-11-30 00:00:00,2002-12-31 00:00:00,2003-01-31 00:00:00
5,NaN,NaN,ACTIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2.0,11,FONDOS DISPONIBLES,NaN,NaN,NaN,NaN,NaN,NaN,285082.82184
7,4.0,1101,Caja,NaN,NaN,NaN,NaN,NaN,NaN,34424.07307
8,6.0,110105,Efectivo,NaN,NaN,NaN,NaN,NaN,NaN,34419.13531
9,6.0,110110,Caja chica,NaN,NaN,NaN,NaN,NaN,NaN,4.93776
10,4.0,1102,Depósitos para encaje,NaN,NaN,NaN,NaN,NaN,NaN,38537.23304
11,6.0,110205,Banco Central del Ecuador,NaN,NaN,NaN,NaN,NaN,NaN,37137.8103

HOJA: PYG
Dimensiones de la muestra: (12, 227)

,0,1,2,3,4,5,6,7,8,9
0,NaN,COMPARATIVO DEL ESTADO DE RESULTADOS NOMINAL,NaN,0,0,0,0,0,0,-0.0
1,NaN,BP PICHINCHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,(en miles de dólares),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,7,8,9,10,11,12,1
4,NaN,CÓDIGO,CUENTA,2002-07-31 00:00:00,2002-08-31 00:00:00,2002-09-30 00:00:00,2002-10-31 00:00:00,2002-11-30 00:00:00,2002-12-31 00:00:00,2003-01-31 00:00:00
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1.0,5,TOTAL INGRESOS,NaN,NaN,NaN,NaN,NaN,NaN,20020.46881
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2.0,51,INTERESES Y DESCUENTOS GANADOS,NaN,NaN,NaN,NaN,NaN,NaN,10494.1974
10,4.0,5101,Depósitos,NaN,NaN,NaN,NaN,NaN,NaN,75.29843
11,4.0,5102,Operaciones interbancarias,NaN,NaN,NaN,NaN,NaN,NaN,0.38197

HOJA: BAL %
Dimensiones de la muestra: (12, 225)

,0,1,2,3,4,5,6,7,8,9
0,NaN,ESTRUCTURA PORCENTUAL DEL COMPARATIVO DE SITUA...,NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaN
1,NaN,BP PICHINCHA,NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaN
2,NaN,( en porcentajes),NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaN
3,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaN
4,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaN
5,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaN
6,NaN,CÓDIGO,CUENTA,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31 00:00:00
7,NaN,0,ACTIVO,NaT,NaT,NaT,NaT,NaT,NaT,NaN
8,NaN,11,FONDOS DISPONIBLES,NaT,NaT,NaT,NaT,NaT,NaT,0.188829
9,NaN,1101,Caja,NaT,NaT,NaT,NaT,NaT,NaT,0.022801
10,NaN,1102,Depósitos para encaje,NaT,NaT,NaT,NaT,NaT,NaT,0.025526
11,NaN,1103,Bancos y otras instituciones financieras,NaT,NaT,NaT,NaT,NaT,NaT,0.113443

In [44]:
# muestra la hoja INDICAD de excel_historico
display(excel_historico.parse("INDICAD"))

,Unnamed: 0,Unnamed: 1,INDICADORES FINANCIEROS,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 215,Unnamed: 216,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220,Unnamed: 221,Unnamed: 222,Unnamed: 223,Unnamed: 224
0,NaN,NaN,BP PICHINCHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,(En porcentajes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,NaN,Intermediación,Intermediación,NaN,NaN,NaN,NaN,NaN,NaN,0.646335,...,0.9357,0.880268,0.832645,0.810721,0.79526,0.773479,0.771517,0.740209,0.772611,0.735453
92,NaN,Cartera Bruta,CARTERA BRUTA,0,0,0,0,0,0,773223.27405,...,7887513.47149,7457779.71628,7240607.70822,7203594.41644,7039611.95697,6935912.98051,6936956.81604,7006014.03131,7090315.67444,7200026.16555
93,NaN,Obligaciones con el Público (Dep. vista+ De...,Depósitos a la vista + Depósitos a plazo,0,0,0,0,0,0,1196320.49622,...,8429531.19782,8472172.60752,8695907.45061,8885414.12962,8851958.96405,8967158.71899,8991321.3696,9464917.13467,9177088.55802,9789924.97436

In [45]:
# Cargar los indicadores históricos
indicad = pd.read_excel(
    excel_historico,
    sheet_name="INDICAD",
    header=None
)

print("Dimensiones:", indicad.shape)

# Inspeccionar encabezados
display(indicad.iloc[:12, :12])

Dimensiones: (95, 225)

,0,1,2,3,4,5,6,7,8,9,10,11
0,NaN,NaN,INDICADORES FINANCIEROS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,BP PICHINCHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,(En porcentajes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,RATIOS,2002-07-31 00:00:00,2002-08-31 00:00:00,2002-09-30 00:00:00,2002-10-31 00:00:00,2002-11-30 00:00:00,2002-12-31 00:00:00,2003-01-31 00:00:00,2003-02-28 00:00:00,2003-03-31 00:00:00
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,INDICE DE CALIDAD DE ACTIVOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,SOLVENCIA,0,0,0,0,0,0,0.0957,0.0975,0.0959
10,102.0,NaN,ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS,NaN,NaN,NaN,NaN,NaN,NaN,0.204643,0.212111,0.206787
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
# Indicadores financieros de interés
patron = (
    r"MOROSIDAD|CARTERA BRUTA|CARTERA IMPRODUCTIVA|"
    r"LIQUIDEZ|COBERTURA|ROA|ROE"
)

# Buscar indicadores en las primeras cuatro columnas
etiquetas = indicad.iloc[:, :4].astype("string")

coincidencias = etiquetas.apply(
    lambda columna: columna.str.contains(
        patron,
        case=False,
        regex=True,
        na=False
    )
).any(axis=1)

# Mostrar filas encontradas
display(
    indicad.loc[coincidencias]
    .iloc[:, :8]
)

,0,1,2,3,4,5,6,7
18,NaN,NaN,INDICE DE LIQUIDEZ,NaN,NaN,NaN,NaN,NaN
28,NaN,Índice de Liquidez,FONDOS DISPONIBLES / TOTAL DEPÓSITOS A CORTO P...,0,0,0,0,0
33,293.0,Rentabilidad sobre activos (ROA),ROA,NaN,NaN,NaN,NaN,NaN
35,295.0,Rentabilidad Patrimonial (ROE),ROE,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,CARTERA BRUTA / (DEPÓSITOS A LA VISTA + DEPÓSI...,NaN,NaN,NaN,NaN,NaN
56,410.0,NaN,Intereses de Cartera de créditos para la micro...,0,0,0,0,0
78,NaN,Morosidad,Morosidad Total,0,0,0,0,0
79,NaN,Cartera Improductiva,TOTAL CARTERA IMPRODUCTIVA,0,0,0,0,0
80,NaN,Cartera Bruta,CARTERA BRUTA,0,0,0,0,0
83,NaN,Cobertura,(Provisiones para créditos incobrables) / TOTA...,0,0,0,0,0
85,NaN,Cartera Improductiva,TOTAL CARTERA IMPRODUCTIVA,0,0,0,0,0
93,NaN,Cartera Bruta,CARTERA BRUTA,0,0,0,0,0

In [ ]:
from pathlib import Path
import pandas as pd
import numpy as np

# Ruta del archivo
series_bp_2020 = "/home/gustavo-paredes/Documents/Developer/Yachay/morosidad-bancos-ecuador/data/raw/series_entidad/BP PICHINCHA DIC 2020 web.xlsx"

# Cargar únicamente los indicadores financieros
historico = pd.read_excel(
    series_bp_2020,
    sheet_name="INDICAD",
    header=None
)

# 1. Extraer fechas
fechas_originales = historico.iloc[6, 4:]

fechas = pd.to_datetime(
    fechas_originales,
    errors="coerce"
)

# Convertir fechas seriales de Excel si fuera necesario
es_numero = fechas_originales.map(
    lambda x: isinstance(
        x, (int, float, np.integer, np.floating)
    )
)

# Convertir fechas seriales de Excel únicamente si existen
if es_numero.any():
    fechas_seriales = pd.to_numeric(
        fechas_originales.loc[es_numero],
        errors="coerce"
    )

    fechas.loc[es_numero] = pd.to_datetime(
        fechas_seriales,
        unit="D",
        origin="1899-12-30",
        errors="coerce"
    )

# 2. Extraer los indicadores
serie_pichincha = pd.DataFrame({
    "fecha": fechas,
    "morosidad_total": pd.to_numeric(
        historico.iloc[78, 3:], errors="coerce"
    ) * 100,

    "cartera_bruta": pd.to_numeric(
        historico.iloc[80, 3:], errors="coerce"
    ),

    "cartera_improductiva": pd.to_numeric(
        historico.iloc[79, 3:], errors="coerce"
    ),

    "liquidez": pd.to_numeric(
        historico.iloc[28, 3:], errors="coerce"
    ) * 100,

    "roa": pd.to_numeric(
        historico.iloc[33, 3:], errors="coerce"
    ) * 100,

    "roe": pd.to_numeric(
        historico.iloc[35, 3:], errors="coerce"
    ) * 100,

    "cobertura": pd.to_numeric(
        historico.iloc[83, 3:], errors="coerce"
    ) * 100
})

# 3. Eliminar períodos sin cartera bruta válida
serie_pichincha = serie_pichincha.loc[
    serie_pichincha["cartera_bruta"] > 0
].copy()

# 4. Normalizar fechas
serie_pichincha["fecha"] = (
    pd.to_datetime(serie_pichincha["fecha"])
    .dt.to_period("M")
    .dt.to_timestamp()
)

# 5. Incorporar la institución
serie_pichincha.insert(
    1, "banco", "BP PICHINCHA"
)

# 6. Reiniciar índices y ordenar
serie_pichincha = (
    serie_pichincha
    .sort_values("fecha")
    .reset_index(drop=True)
)

# Visualización
display(serie_pichincha.head())
display(serie_pichincha.tail())

ValueError: 'Series([], Name: 6, dtype: object)' is not compatible with origin='1899-12-30'; it must be numeric with a unit specified